/* tslint:disable */

/**
 * SubmissionStatus is the lifecycle state of a submission.
 * DRAFT → PENDING → (FURTHER_INFO_REQUIRED → PENDING) → APPROVED → COMPLETED,
 * or REJECTED. Expenses settled via SETTLEMENT_COMMITTEE_ACCOUNT and income
 * submissions are COMPLETED directly upon approval.
 */
type V1SubmissionStatus =
  'SUBMISSION_STATUS_UNSPECIFIED' |
  'SUBMISSION_STATUS_DRAFT' |
  'SUBMISSION_STATUS_PENDING' |
  'SUBMISSION_STATUS_FURTHER_INFO_REQUIRED' |
  'SUBMISSION_STATUS_REJECTED' |
  'SUBMISSION_STATUS_APPROVED' |
  'SUBMISSION_STATUS_COMPLETED';
module V1SubmissionStatus {
  export const SUBMISSION_STATUS_UNSPECIFIED: V1SubmissionStatus = 'SUBMISSION_STATUS_UNSPECIFIED';
  export const SUBMISSION_STATUS_DRAFT: V1SubmissionStatus = 'SUBMISSION_STATUS_DRAFT';
  export const SUBMISSION_STATUS_PENDING: V1SubmissionStatus = 'SUBMISSION_STATUS_PENDING';
  export const SUBMISSION_STATUS_FURTHER_INFO_REQUIRED: V1SubmissionStatus = 'SUBMISSION_STATUS_FURTHER_INFO_REQUIRED';
  export const SUBMISSION_STATUS_REJECTED: V1SubmissionStatus = 'SUBMISSION_STATUS_REJECTED';
  export const SUBMISSION_STATUS_APPROVED: V1SubmissionStatus = 'SUBMISSION_STATUS_APPROVED';
  export const SUBMISSION_STATUS_COMPLETED: V1SubmissionStatus = 'SUBMISSION_STATUS_COMPLETED';
  export function values(): V1SubmissionStatus[] {
    return [
      SUBMISSION_STATUS_UNSPECIFIED,
      SUBMISSION_STATUS_DRAFT,
      SUBMISSION_STATUS_PENDING,
      SUBMISSION_STATUS_FURTHER_INFO_REQUIRED,
      SUBMISSION_STATUS_REJECTED,
      SUBMISSION_STATUS_APPROVED,
      SUBMISSION_STATUS_COMPLETED
    ];
  }
}

export { V1SubmissionStatus }