// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"github.com/pixlcrashr/vsfv/pkg/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newAccount(db *gorm.DB, opts ...gen.DOOption) account {
	_account := account{}

	_account.accountDo.UseDB(db, opts...)
	_account.accountDo.UseModel(&model.Account{})

	tableName := _account.accountDo.TableName()
	_account.ALL = field.NewAsterisk(tableName)
	_account.ID = field.NewField(tableName, "id")
	_account.CustomID = field.NewString(tableName, "custom_id")
	_account.OrganizationID = field.NewField(tableName, "organization_id")
	_account.ParentAccountID = field.NewField(tableName, "parent_account_id")
	_account.DisplayName = field.NewString(tableName, "display_name")
	_account.DisplayCode = field.NewString(tableName, "display_code")
	_account.DisplayDescription = field.NewString(tableName, "display_description")
	_account.IsContainer = field.NewBool(tableName, "is_container")
	_account.IsArchived = field.NewBool(tableName, "is_archived")
	_account.UpdatedAt = field.NewTime(tableName, "updated_at")
	_account.CreatedAt = field.NewTime(tableName, "created_at")
	_account.ChildAccounts = accountHasManyChildAccounts{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ChildAccounts", "model.Account"),
		Organization: struct {
			field.RelationField
			SubmissionSettings struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			AccountGroupAssignments struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
				}
			}
			AccountGroups struct {
				field.RelationField
			}
			Accounts struct {
				field.RelationField
			}
			BudgetRevisions struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Budget struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					BudgetRevisions struct {
						field.RelationField
					}
					BudgetAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
			}
			BudgetRevisionAccountValues struct {
				field.RelationField
			}
			BudgetAccountValues struct {
				field.RelationField
			}
			Budgets struct {
				field.RelationField
			}
			LedgerYears struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			LedgerAccounts struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				CreditTransactions struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					CreditLedgerAccount struct {
						field.RelationField
					}
					DebitLedgerAccount struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
				}
				DebitTransactions struct {
					field.RelationField
				}
			}
			ReportTemplates struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Reports struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Transactions struct {
				field.RelationField
			}
			TransactionAssignments struct {
				field.RelationField
			}
			Committees struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				PaymentAccounts struct {
					field.RelationField
					Committee struct {
						field.RelationField
					}
				}
				Submissions struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Committee struct {
						field.RelationField
					}
					CreatedBy struct {
						field.RelationField
						UserIdentities struct {
							field.RelationField
							User struct {
								field.RelationField
							}
						}
					}
				}
			}
			Submissions struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("ChildAccounts.Organization", "model.Organization"),
			SubmissionSettings: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.SubmissionSettings", "model.OrganizationSubmissionSettings"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.SubmissionSettings.Organization", "model.Organization"),
				},
			},
			AccountGroupAssignments: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.AccountGroupAssignments", "model.AccountGroupAssignment"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.AccountGroupAssignments.Organization", "model.Organization"),
				},
				AccountGroup: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.AccountGroupAssignments.AccountGroup", "model.AccountGroup"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.AccountGroupAssignments.AccountGroup.Organization", "model.Organization"),
					},
					AccountGroupAssignments: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.AccountGroupAssignments.AccountGroup.AccountGroupAssignments", "model.AccountGroupAssignment"),
					},
				},
				Account: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.AccountGroupAssignments.Account", "model.Account"),
				},
			},
			AccountGroups: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.AccountGroups", "model.AccountGroup"),
			},
			Accounts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.Accounts", "model.Account"),
			},
			BudgetRevisions: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Budget struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					BudgetRevisions struct {
						field.RelationField
					}
					BudgetAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.BudgetRevisions", "model.BudgetRevision"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.BudgetRevisions.Organization", "model.Organization"),
				},
				Budget: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					BudgetRevisions struct {
						field.RelationField
					}
					BudgetAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.BudgetRevisions.Budget", "model.Budget"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.BudgetRevisions.Budget.Organization", "model.Organization"),
					},
					BudgetRevisions: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.BudgetRevisions.Budget.BudgetRevisions", "model.BudgetRevision"),
					},
					BudgetAccountValues: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.BudgetRevisions.Budget.BudgetAccountValues", "model.BudgetAccountValue"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ChildAccounts.Organization.BudgetRevisions.Budget.BudgetAccountValues.Organization", "model.Organization"),
						},
						Budget: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ChildAccounts.Organization.BudgetRevisions.Budget.BudgetAccountValues.Budget", "model.Budget"),
						},
						Account: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ChildAccounts.Organization.BudgetRevisions.Budget.BudgetAccountValues.Account", "model.Account"),
						},
					},
				},
				BudgetRevisionAccountValues: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.BudgetRevisions.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.BudgetRevisions.BudgetRevisionAccountValues.Organization", "model.Organization"),
					},
					Budget: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.BudgetRevisions.BudgetRevisionAccountValues.Budget", "model.Budget"),
					},
					BudgetRevision: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.BudgetRevisions.BudgetRevisionAccountValues.BudgetRevision", "model.BudgetRevision"),
					},
					Account: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.BudgetRevisions.BudgetRevisionAccountValues.Account", "model.Account"),
					},
				},
			},
			BudgetRevisionAccountValues: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
			},
			BudgetAccountValues: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.BudgetAccountValues", "model.BudgetAccountValue"),
			},
			Budgets: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.Budgets", "model.Budget"),
			},
			LedgerYears: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.LedgerYears", "model.LedgerYear"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.LedgerYears.Organization", "model.Organization"),
				},
			},
			LedgerAccounts: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				CreditTransactions struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					CreditLedgerAccount struct {
						field.RelationField
					}
					DebitLedgerAccount struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
				}
				DebitTransactions struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.LedgerAccounts", "model.LedgerAccount"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.LedgerAccounts.Organization", "model.Organization"),
				},
				CreditTransactions: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					CreditLedgerAccount struct {
						field.RelationField
					}
					DebitLedgerAccount struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.LedgerAccounts.CreditTransactions", "model.Transaction_"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.LedgerAccounts.CreditTransactions.Organization", "model.Organization"),
					},
					CreditLedgerAccount: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.LedgerAccounts.CreditTransactions.CreditLedgerAccount", "model.LedgerAccount"),
					},
					DebitLedgerAccount: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.LedgerAccounts.CreditTransactions.DebitLedgerAccount", "model.LedgerAccount"),
					},
					TransactionAssignments: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.LedgerAccounts.CreditTransactions.TransactionAssignments", "model.TransactionAssignment"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ChildAccounts.Organization.LedgerAccounts.CreditTransactions.TransactionAssignments.Organization", "model.Organization"),
						},
						Transaction: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ChildAccounts.Organization.LedgerAccounts.CreditTransactions.TransactionAssignments.Transaction", "model.Transaction_"),
						},
						Account: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ChildAccounts.Organization.LedgerAccounts.CreditTransactions.TransactionAssignments.Account", "model.Account"),
						},
					},
				},
				DebitTransactions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.LedgerAccounts.DebitTransactions", "model.Transaction_"),
				},
			},
			ReportTemplates: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.ReportTemplates", "model.ReportTemplate"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.ReportTemplates.Organization", "model.Organization"),
				},
			},
			Reports: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.Reports", "model.Report"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.Reports.Organization", "model.Organization"),
				},
			},
			Transactions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.Transactions", "model.Transaction_"),
			},
			TransactionAssignments: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.TransactionAssignments", "model.TransactionAssignment"),
			},
			Committees: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				PaymentAccounts struct {
					field.RelationField
					Committee struct {
						field.RelationField
					}
				}
				Submissions struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Committee struct {
						field.RelationField
					}
					CreatedBy struct {
						field.RelationField
						UserIdentities struct {
							field.RelationField
							User struct {
								field.RelationField
							}
						}
					}
				}
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.Committees", "model.Committee"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.Committees.Organization", "model.Organization"),
				},
				PaymentAccounts: struct {
					field.RelationField
					Committee struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.Committees.PaymentAccounts", "model.CommitteePaymentAccount"),
					Committee: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.Committees.PaymentAccounts.Committee", "model.Committee"),
					},
				},
				Submissions: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Committee struct {
						field.RelationField
					}
					CreatedBy struct {
						field.RelationField
						UserIdentities struct {
							field.RelationField
							User struct {
								field.RelationField
							}
						}
					}
				}{
					RelationField: field.NewRelation("ChildAccounts.Organization.Committees.Submissions", "model.Submission"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.Committees.Submissions.Organization", "model.Organization"),
					},
					Committee: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.Committees.Submissions.Committee", "model.Committee"),
					},
					CreatedBy: struct {
						field.RelationField
						UserIdentities struct {
							field.RelationField
							User struct {
								field.RelationField
							}
						}
					}{
						RelationField: field.NewRelation("ChildAccounts.Organization.Committees.Submissions.CreatedBy", "model.User"),
						UserIdentities: struct {
							field.RelationField
							User struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("ChildAccounts.Organization.Committees.Submissions.CreatedBy.UserIdentities", "model.UserIdentity"),
							User: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("ChildAccounts.Organization.Committees.Submissions.CreatedBy.UserIdentities.User", "model.User"),
							},
						},
					},
				},
			},
			Submissions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ChildAccounts.Organization.Submissions", "model.Submission"),
			},
		},
		ParentAccount: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("ChildAccounts.ParentAccount", "model.Account"),
		},
		ChildAccounts: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("ChildAccounts.ChildAccounts", "model.Account"),
		},
		AccountGroupAssignments: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("ChildAccounts.AccountGroupAssignments", "model.AccountGroupAssignment"),
		},
		BudgetRevisionAccountValues: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("ChildAccounts.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
		},
		BudgetAccountValues: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("ChildAccounts.BudgetAccountValues", "model.BudgetAccountValue"),
		},
		TransactionAssignments: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("ChildAccounts.TransactionAssignments", "model.TransactionAssignment"),
		},
	}

	_account.AccountGroupAssignments = accountHasManyAccountGroupAssignments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AccountGroupAssignments", "model.AccountGroupAssignment"),
	}

	_account.BudgetRevisionAccountValues = accountHasManyBudgetRevisionAccountValues{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
	}

	_account.BudgetAccountValues = accountHasManyBudgetAccountValues{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("BudgetAccountValues", "model.BudgetAccountValue"),
	}

	_account.TransactionAssignments = accountHasManyTransactionAssignments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("TransactionAssignments", "model.TransactionAssignment"),
	}

	_account.Organization = accountBelongsToOrganization{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Organization", "model.Organization"),
	}

	_account.ParentAccount = accountBelongsToParentAccount{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ParentAccount", "model.Account"),
	}

	_account.fillFieldMap()

	return _account
}

type account struct {
	accountDo accountDo

	ALL                field.Asterisk
	ID                 field.Field
	CustomID           field.String
	OrganizationID     field.Field
	ParentAccountID    field.Field
	DisplayName        field.String
	DisplayCode        field.String
	DisplayDescription field.String
	IsContainer        field.Bool
	IsArchived         field.Bool
	UpdatedAt          field.Time
	CreatedAt          field.Time
	ChildAccounts      accountHasManyChildAccounts

	AccountGroupAssignments accountHasManyAccountGroupAssignments

	BudgetRevisionAccountValues accountHasManyBudgetRevisionAccountValues

	BudgetAccountValues accountHasManyBudgetAccountValues

	TransactionAssignments accountHasManyTransactionAssignments

	Organization accountBelongsToOrganization

	ParentAccount accountBelongsToParentAccount

	fieldMap map[string]field.Expr
}

func (a account) Table(newTableName string) *account {
	a.accountDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a account) As(alias string) *account {
	a.accountDo.DO = *(a.accountDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *account) updateTableName(table string) *account {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewField(table, "id")
	a.CustomID = field.NewString(table, "custom_id")
	a.OrganizationID = field.NewField(table, "organization_id")
	a.ParentAccountID = field.NewField(table, "parent_account_id")
	a.DisplayName = field.NewString(table, "display_name")
	a.DisplayCode = field.NewString(table, "display_code")
	a.DisplayDescription = field.NewString(table, "display_description")
	a.IsContainer = field.NewBool(table, "is_container")
	a.IsArchived = field.NewBool(table, "is_archived")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *account) WithContext(ctx context.Context) IAccountDo { return a.accountDo.WithContext(ctx) }

func (a account) TableName() string { return a.accountDo.TableName() }

func (a account) Alias() string { return a.accountDo.Alias() }

func (a account) Columns(cols ...field.Expr) gen.Columns { return a.accountDo.Columns(cols...) }

func (a *account) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *account) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 18)
	a.fieldMap["id"] = a.ID
	a.fieldMap["custom_id"] = a.CustomID
	a.fieldMap["organization_id"] = a.OrganizationID
	a.fieldMap["parent_account_id"] = a.ParentAccountID
	a.fieldMap["display_name"] = a.DisplayName
	a.fieldMap["display_code"] = a.DisplayCode
	a.fieldMap["display_description"] = a.DisplayDescription
	a.fieldMap["is_container"] = a.IsContainer
	a.fieldMap["is_archived"] = a.IsArchived
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["created_at"] = a.CreatedAt

}

func (a account) clone(db *gorm.DB) account {
	a.accountDo.ReplaceConnPool(db.Statement.ConnPool)
	a.ChildAccounts.db = db.Session(&gorm.Session{Initialized: true})
	a.ChildAccounts.db.Statement.ConnPool = db.Statement.ConnPool
	a.AccountGroupAssignments.db = db.Session(&gorm.Session{Initialized: true})
	a.AccountGroupAssignments.db.Statement.ConnPool = db.Statement.ConnPool
	a.BudgetRevisionAccountValues.db = db.Session(&gorm.Session{Initialized: true})
	a.BudgetRevisionAccountValues.db.Statement.ConnPool = db.Statement.ConnPool
	a.BudgetAccountValues.db = db.Session(&gorm.Session{Initialized: true})
	a.BudgetAccountValues.db.Statement.ConnPool = db.Statement.ConnPool
	a.TransactionAssignments.db = db.Session(&gorm.Session{Initialized: true})
	a.TransactionAssignments.db.Statement.ConnPool = db.Statement.ConnPool
	a.Organization.db = db.Session(&gorm.Session{Initialized: true})
	a.Organization.db.Statement.ConnPool = db.Statement.ConnPool
	a.ParentAccount.db = db.Session(&gorm.Session{Initialized: true})
	a.ParentAccount.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a account) replaceDB(db *gorm.DB) account {
	a.accountDo.ReplaceDB(db)
	a.ChildAccounts.db = db.Session(&gorm.Session{})
	a.AccountGroupAssignments.db = db.Session(&gorm.Session{})
	a.BudgetRevisionAccountValues.db = db.Session(&gorm.Session{})
	a.BudgetAccountValues.db = db.Session(&gorm.Session{})
	a.TransactionAssignments.db = db.Session(&gorm.Session{})
	a.Organization.db = db.Session(&gorm.Session{})
	a.ParentAccount.db = db.Session(&gorm.Session{})
	return a
}

type accountHasManyChildAccounts struct {
	db *gorm.DB

	field.RelationField

	Organization struct {
		field.RelationField
		SubmissionSettings struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		AccountGroupAssignments struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroup struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}
			Account struct {
				field.RelationField
			}
		}
		AccountGroups struct {
			field.RelationField
		}
		Accounts struct {
			field.RelationField
		}
		BudgetRevisions struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			Budget struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				BudgetRevisions struct {
					field.RelationField
				}
				BudgetAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
			}
			BudgetRevisionAccountValues struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Budget struct {
					field.RelationField
				}
				BudgetRevision struct {
					field.RelationField
				}
				Account struct {
					field.RelationField
				}
			}
		}
		BudgetRevisionAccountValues struct {
			field.RelationField
		}
		BudgetAccountValues struct {
			field.RelationField
		}
		Budgets struct {
			field.RelationField
		}
		LedgerYears struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		LedgerAccounts struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			CreditTransactions struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				CreditLedgerAccount struct {
					field.RelationField
				}
				DebitLedgerAccount struct {
					field.RelationField
				}
				TransactionAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
			}
			DebitTransactions struct {
				field.RelationField
			}
		}
		ReportTemplates struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Reports struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Transactions struct {
			field.RelationField
		}
		TransactionAssignments struct {
			field.RelationField
		}
		Committees struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			PaymentAccounts struct {
				field.RelationField
				Committee struct {
					field.RelationField
				}
			}
			Submissions struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Committee struct {
					field.RelationField
				}
				CreatedBy struct {
					field.RelationField
					UserIdentities struct {
						field.RelationField
						User struct {
							field.RelationField
						}
					}
				}
			}
		}
		Submissions struct {
			field.RelationField
		}
	}
	ParentAccount struct {
		field.RelationField
	}
	ChildAccounts struct {
		field.RelationField
	}
	AccountGroupAssignments struct {
		field.RelationField
	}
	BudgetRevisionAccountValues struct {
		field.RelationField
	}
	BudgetAccountValues struct {
		field.RelationField
	}
	TransactionAssignments struct {
		field.RelationField
	}
}

func (a accountHasManyChildAccounts) Where(conds ...field.Expr) *accountHasManyChildAccounts {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a accountHasManyChildAccounts) WithContext(ctx context.Context) *accountHasManyChildAccounts {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a accountHasManyChildAccounts) Session(session *gorm.Session) *accountHasManyChildAccounts {
	a.db = a.db.Session(session)
	return &a
}

func (a accountHasManyChildAccounts) Model(m *model.Account) *accountHasManyChildAccountsTx {
	return &accountHasManyChildAccountsTx{a.db.Model(m).Association(a.Name())}
}

func (a accountHasManyChildAccounts) Unscoped() *accountHasManyChildAccounts {
	a.db = a.db.Unscoped()
	return &a
}

type accountHasManyChildAccountsTx struct{ tx *gorm.Association }

func (a accountHasManyChildAccountsTx) Find() (result []*model.Account, err error) {
	return result, a.tx.Find(&result)
}

func (a accountHasManyChildAccountsTx) Append(values ...*model.Account) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a accountHasManyChildAccountsTx) Replace(values ...*model.Account) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a accountHasManyChildAccountsTx) Delete(values ...*model.Account) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a accountHasManyChildAccountsTx) Clear() error {
	return a.tx.Clear()
}

func (a accountHasManyChildAccountsTx) Count() int64 {
	return a.tx.Count()
}

func (a accountHasManyChildAccountsTx) Unscoped() *accountHasManyChildAccountsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type accountHasManyAccountGroupAssignments struct {
	db *gorm.DB

	field.RelationField
}

func (a accountHasManyAccountGroupAssignments) Where(conds ...field.Expr) *accountHasManyAccountGroupAssignments {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a accountHasManyAccountGroupAssignments) WithContext(ctx context.Context) *accountHasManyAccountGroupAssignments {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a accountHasManyAccountGroupAssignments) Session(session *gorm.Session) *accountHasManyAccountGroupAssignments {
	a.db = a.db.Session(session)
	return &a
}

func (a accountHasManyAccountGroupAssignments) Model(m *model.Account) *accountHasManyAccountGroupAssignmentsTx {
	return &accountHasManyAccountGroupAssignmentsTx{a.db.Model(m).Association(a.Name())}
}

func (a accountHasManyAccountGroupAssignments) Unscoped() *accountHasManyAccountGroupAssignments {
	a.db = a.db.Unscoped()
	return &a
}

type accountHasManyAccountGroupAssignmentsTx struct{ tx *gorm.Association }

func (a accountHasManyAccountGroupAssignmentsTx) Find() (result []*model.AccountGroupAssignment, err error) {
	return result, a.tx.Find(&result)
}

func (a accountHasManyAccountGroupAssignmentsTx) Append(values ...*model.AccountGroupAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a accountHasManyAccountGroupAssignmentsTx) Replace(values ...*model.AccountGroupAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a accountHasManyAccountGroupAssignmentsTx) Delete(values ...*model.AccountGroupAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a accountHasManyAccountGroupAssignmentsTx) Clear() error {
	return a.tx.Clear()
}

func (a accountHasManyAccountGroupAssignmentsTx) Count() int64 {
	return a.tx.Count()
}

func (a accountHasManyAccountGroupAssignmentsTx) Unscoped() *accountHasManyAccountGroupAssignmentsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type accountHasManyBudgetRevisionAccountValues struct {
	db *gorm.DB

	field.RelationField
}

func (a accountHasManyBudgetRevisionAccountValues) Where(conds ...field.Expr) *accountHasManyBudgetRevisionAccountValues {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a accountHasManyBudgetRevisionAccountValues) WithContext(ctx context.Context) *accountHasManyBudgetRevisionAccountValues {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a accountHasManyBudgetRevisionAccountValues) Session(session *gorm.Session) *accountHasManyBudgetRevisionAccountValues {
	a.db = a.db.Session(session)
	return &a
}

func (a accountHasManyBudgetRevisionAccountValues) Model(m *model.Account) *accountHasManyBudgetRevisionAccountValuesTx {
	return &accountHasManyBudgetRevisionAccountValuesTx{a.db.Model(m).Association(a.Name())}
}

func (a accountHasManyBudgetRevisionAccountValues) Unscoped() *accountHasManyBudgetRevisionAccountValues {
	a.db = a.db.Unscoped()
	return &a
}

type accountHasManyBudgetRevisionAccountValuesTx struct{ tx *gorm.Association }

func (a accountHasManyBudgetRevisionAccountValuesTx) Find() (result []*model.BudgetRevisionAccountValue, err error) {
	return result, a.tx.Find(&result)
}

func (a accountHasManyBudgetRevisionAccountValuesTx) Append(values ...*model.BudgetRevisionAccountValue) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a accountHasManyBudgetRevisionAccountValuesTx) Replace(values ...*model.BudgetRevisionAccountValue) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a accountHasManyBudgetRevisionAccountValuesTx) Delete(values ...*model.BudgetRevisionAccountValue) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a accountHasManyBudgetRevisionAccountValuesTx) Clear() error {
	return a.tx.Clear()
}

func (a accountHasManyBudgetRevisionAccountValuesTx) Count() int64 {
	return a.tx.Count()
}

func (a accountHasManyBudgetRevisionAccountValuesTx) Unscoped() *accountHasManyBudgetRevisionAccountValuesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type accountHasManyBudgetAccountValues struct {
	db *gorm.DB

	field.RelationField
}

func (a accountHasManyBudgetAccountValues) Where(conds ...field.Expr) *accountHasManyBudgetAccountValues {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a accountHasManyBudgetAccountValues) WithContext(ctx context.Context) *accountHasManyBudgetAccountValues {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a accountHasManyBudgetAccountValues) Session(session *gorm.Session) *accountHasManyBudgetAccountValues {
	a.db = a.db.Session(session)
	return &a
}

func (a accountHasManyBudgetAccountValues) Model(m *model.Account) *accountHasManyBudgetAccountValuesTx {
	return &accountHasManyBudgetAccountValuesTx{a.db.Model(m).Association(a.Name())}
}

func (a accountHasManyBudgetAccountValues) Unscoped() *accountHasManyBudgetAccountValues {
	a.db = a.db.Unscoped()
	return &a
}

type accountHasManyBudgetAccountValuesTx struct{ tx *gorm.Association }

func (a accountHasManyBudgetAccountValuesTx) Find() (result []*model.BudgetAccountValue, err error) {
	return result, a.tx.Find(&result)
}

func (a accountHasManyBudgetAccountValuesTx) Append(values ...*model.BudgetAccountValue) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a accountHasManyBudgetAccountValuesTx) Replace(values ...*model.BudgetAccountValue) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a accountHasManyBudgetAccountValuesTx) Delete(values ...*model.BudgetAccountValue) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a accountHasManyBudgetAccountValuesTx) Clear() error {
	return a.tx.Clear()
}

func (a accountHasManyBudgetAccountValuesTx) Count() int64 {
	return a.tx.Count()
}

func (a accountHasManyBudgetAccountValuesTx) Unscoped() *accountHasManyBudgetAccountValuesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type accountHasManyTransactionAssignments struct {
	db *gorm.DB

	field.RelationField
}

func (a accountHasManyTransactionAssignments) Where(conds ...field.Expr) *accountHasManyTransactionAssignments {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a accountHasManyTransactionAssignments) WithContext(ctx context.Context) *accountHasManyTransactionAssignments {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a accountHasManyTransactionAssignments) Session(session *gorm.Session) *accountHasManyTransactionAssignments {
	a.db = a.db.Session(session)
	return &a
}

func (a accountHasManyTransactionAssignments) Model(m *model.Account) *accountHasManyTransactionAssignmentsTx {
	return &accountHasManyTransactionAssignmentsTx{a.db.Model(m).Association(a.Name())}
}

func (a accountHasManyTransactionAssignments) Unscoped() *accountHasManyTransactionAssignments {
	a.db = a.db.Unscoped()
	return &a
}

type accountHasManyTransactionAssignmentsTx struct{ tx *gorm.Association }

func (a accountHasManyTransactionAssignmentsTx) Find() (result []*model.TransactionAssignment, err error) {
	return result, a.tx.Find(&result)
}

func (a accountHasManyTransactionAssignmentsTx) Append(values ...*model.TransactionAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a accountHasManyTransactionAssignmentsTx) Replace(values ...*model.TransactionAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a accountHasManyTransactionAssignmentsTx) Delete(values ...*model.TransactionAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a accountHasManyTransactionAssignmentsTx) Clear() error {
	return a.tx.Clear()
}

func (a accountHasManyTransactionAssignmentsTx) Count() int64 {
	return a.tx.Count()
}

func (a accountHasManyTransactionAssignmentsTx) Unscoped() *accountHasManyTransactionAssignmentsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type accountBelongsToOrganization struct {
	db *gorm.DB

	field.RelationField
}

func (a accountBelongsToOrganization) Where(conds ...field.Expr) *accountBelongsToOrganization {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a accountBelongsToOrganization) WithContext(ctx context.Context) *accountBelongsToOrganization {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a accountBelongsToOrganization) Session(session *gorm.Session) *accountBelongsToOrganization {
	a.db = a.db.Session(session)
	return &a
}

func (a accountBelongsToOrganization) Model(m *model.Account) *accountBelongsToOrganizationTx {
	return &accountBelongsToOrganizationTx{a.db.Model(m).Association(a.Name())}
}

func (a accountBelongsToOrganization) Unscoped() *accountBelongsToOrganization {
	a.db = a.db.Unscoped()
	return &a
}

type accountBelongsToOrganizationTx struct{ tx *gorm.Association }

func (a accountBelongsToOrganizationTx) Find() (result *model.Organization, err error) {
	return result, a.tx.Find(&result)
}

func (a accountBelongsToOrganizationTx) Append(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a accountBelongsToOrganizationTx) Replace(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a accountBelongsToOrganizationTx) Delete(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a accountBelongsToOrganizationTx) Clear() error {
	return a.tx.Clear()
}

func (a accountBelongsToOrganizationTx) Count() int64 {
	return a.tx.Count()
}

func (a accountBelongsToOrganizationTx) Unscoped() *accountBelongsToOrganizationTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type accountBelongsToParentAccount struct {
	db *gorm.DB

	field.RelationField
}

func (a accountBelongsToParentAccount) Where(conds ...field.Expr) *accountBelongsToParentAccount {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a accountBelongsToParentAccount) WithContext(ctx context.Context) *accountBelongsToParentAccount {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a accountBelongsToParentAccount) Session(session *gorm.Session) *accountBelongsToParentAccount {
	a.db = a.db.Session(session)
	return &a
}

func (a accountBelongsToParentAccount) Model(m *model.Account) *accountBelongsToParentAccountTx {
	return &accountBelongsToParentAccountTx{a.db.Model(m).Association(a.Name())}
}

func (a accountBelongsToParentAccount) Unscoped() *accountBelongsToParentAccount {
	a.db = a.db.Unscoped()
	return &a
}

type accountBelongsToParentAccountTx struct{ tx *gorm.Association }

func (a accountBelongsToParentAccountTx) Find() (result *model.Account, err error) {
	return result, a.tx.Find(&result)
}

func (a accountBelongsToParentAccountTx) Append(values ...*model.Account) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a accountBelongsToParentAccountTx) Replace(values ...*model.Account) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a accountBelongsToParentAccountTx) Delete(values ...*model.Account) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a accountBelongsToParentAccountTx) Clear() error {
	return a.tx.Clear()
}

func (a accountBelongsToParentAccountTx) Count() int64 {
	return a.tx.Count()
}

func (a accountBelongsToParentAccountTx) Unscoped() *accountBelongsToParentAccountTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type accountDo struct{ gen.DO }

type IAccountDo interface {
	gen.SubQuery
	Debug() IAccountDo
	WithContext(ctx context.Context) IAccountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAccountDo
	WriteDB() IAccountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAccountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAccountDo
	Not(conds ...gen.Condition) IAccountDo
	Or(conds ...gen.Condition) IAccountDo
	Select(conds ...field.Expr) IAccountDo
	Where(conds ...gen.Condition) IAccountDo
	Order(conds ...field.Expr) IAccountDo
	Distinct(cols ...field.Expr) IAccountDo
	Omit(cols ...field.Expr) IAccountDo
	Join(table schema.Tabler, on ...field.Expr) IAccountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAccountDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAccountDo
	Group(cols ...field.Expr) IAccountDo
	Having(conds ...gen.Condition) IAccountDo
	Limit(limit int) IAccountDo
	Offset(offset int) IAccountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAccountDo
	Unscoped() IAccountDo
	Create(values ...*model.Account) error
	CreateInBatches(values []*model.Account, batchSize int) error
	Save(values ...*model.Account) error
	First() (*model.Account, error)
	Take() (*model.Account, error)
	Last() (*model.Account, error)
	Find() ([]*model.Account, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Account, err error)
	FindInBatches(result *[]*model.Account, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Account) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAccountDo
	Assign(attrs ...field.AssignExpr) IAccountDo
	Joins(fields ...field.RelationField) IAccountDo
	Preload(fields ...field.RelationField) IAccountDo
	FirstOrInit() (*model.Account, error)
	FirstOrCreate() (*model.Account, error)
	FindByPage(offset int, limit int) (result []*model.Account, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAccountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a accountDo) Debug() IAccountDo {
	return a.withDO(a.DO.Debug())
}

func (a accountDo) WithContext(ctx context.Context) IAccountDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a accountDo) ReadDB() IAccountDo {
	return a.Clauses(dbresolver.Read)
}

func (a accountDo) WriteDB() IAccountDo {
	return a.Clauses(dbresolver.Write)
}

func (a accountDo) Session(config *gorm.Session) IAccountDo {
	return a.withDO(a.DO.Session(config))
}

func (a accountDo) Clauses(conds ...clause.Expression) IAccountDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a accountDo) Returning(value interface{}, columns ...string) IAccountDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a accountDo) Not(conds ...gen.Condition) IAccountDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a accountDo) Or(conds ...gen.Condition) IAccountDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a accountDo) Select(conds ...field.Expr) IAccountDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a accountDo) Where(conds ...gen.Condition) IAccountDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a accountDo) Order(conds ...field.Expr) IAccountDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a accountDo) Distinct(cols ...field.Expr) IAccountDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a accountDo) Omit(cols ...field.Expr) IAccountDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a accountDo) Join(table schema.Tabler, on ...field.Expr) IAccountDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a accountDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAccountDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a accountDo) RightJoin(table schema.Tabler, on ...field.Expr) IAccountDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a accountDo) Group(cols ...field.Expr) IAccountDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a accountDo) Having(conds ...gen.Condition) IAccountDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a accountDo) Limit(limit int) IAccountDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a accountDo) Offset(offset int) IAccountDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a accountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAccountDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a accountDo) Unscoped() IAccountDo {
	return a.withDO(a.DO.Unscoped())
}

func (a accountDo) Create(values ...*model.Account) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a accountDo) CreateInBatches(values []*model.Account, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a accountDo) Save(values ...*model.Account) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a accountDo) First() (*model.Account, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Account), nil
	}
}

func (a accountDo) Take() (*model.Account, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Account), nil
	}
}

func (a accountDo) Last() (*model.Account, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Account), nil
	}
}

func (a accountDo) Find() ([]*model.Account, error) {
	result, err := a.DO.Find()
	return result.([]*model.Account), err
}

func (a accountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Account, err error) {
	buf := make([]*model.Account, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a accountDo) FindInBatches(result *[]*model.Account, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a accountDo) Attrs(attrs ...field.AssignExpr) IAccountDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a accountDo) Assign(attrs ...field.AssignExpr) IAccountDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a accountDo) Joins(fields ...field.RelationField) IAccountDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a accountDo) Preload(fields ...field.RelationField) IAccountDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a accountDo) FirstOrInit() (*model.Account, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Account), nil
	}
}

func (a accountDo) FirstOrCreate() (*model.Account, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Account), nil
	}
}

func (a accountDo) FindByPage(offset int, limit int) (result []*model.Account, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a accountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a accountDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a accountDo) Delete(models ...*model.Account) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *accountDo) withDO(do gen.Dao) *accountDo {
	a.DO = *do.(*gen.DO)
	return a
}
