// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"github.com/pixlcrashr/vsfv/pkg/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newBudgetAccountValue(db *gorm.DB, opts ...gen.DOOption) budgetAccountValue {
	_budgetAccountValue := budgetAccountValue{}

	_budgetAccountValue.budgetAccountValueDo.UseDB(db, opts...)
	_budgetAccountValue.budgetAccountValueDo.UseModel(&model.BudgetAccountValue{})

	tableName := _budgetAccountValue.budgetAccountValueDo.TableName()
	_budgetAccountValue.ALL = field.NewAsterisk(tableName)
	_budgetAccountValue.ID = field.NewField(tableName, "id")
	_budgetAccountValue.CustomID = field.NewString(tableName, "custom_id")
	_budgetAccountValue.OrganizationID = field.NewField(tableName, "organization_id")
	_budgetAccountValue.BudgetID = field.NewField(tableName, "budget_id")
	_budgetAccountValue.AccountID = field.NewField(tableName, "account_id")
	_budgetAccountValue.Value = field.NewField(tableName, "value")
	_budgetAccountValue.UpdatedAt = field.NewTime(tableName, "updated_at")
	_budgetAccountValue.CreatedAt = field.NewTime(tableName, "created_at")
	_budgetAccountValue.Organization = budgetAccountValueBelongsToOrganization{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Organization", "model.Organization"),
		SubmissionSettings: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Organization.SubmissionSettings", "model.OrganizationSubmissionSettings"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.SubmissionSettings.Organization", "model.Organization"),
			},
		},
		AccountGroupAssignments: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroup struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}
			Account struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
				BudgetAccountValues struct {
					field.RelationField
				}
				TransactionAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditLedgerAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitLedgerAccount struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
			}
		}{
			RelationField: field.NewRelation("Organization.AccountGroupAssignments", "model.AccountGroupAssignment"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.AccountGroupAssignments.Organization", "model.Organization"),
			},
			AccountGroup: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Organization.AccountGroupAssignments.AccountGroup", "model.AccountGroup"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.AccountGroup.Organization", "model.Organization"),
				},
				AccountGroupAssignments: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.AccountGroup.AccountGroupAssignments", "model.AccountGroupAssignment"),
				},
			},
			Account: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
				BudgetAccountValues struct {
					field.RelationField
				}
				TransactionAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditLedgerAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitLedgerAccount struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account", "model.Account"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.Organization", "model.Organization"),
				},
				ParentAccount: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.ParentAccount", "model.Account"),
				},
				ChildAccounts: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.ChildAccounts", "model.Account"),
				},
				AccountGroupAssignments: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.AccountGroupAssignments", "model.AccountGroupAssignment"),
				},
				BudgetRevisionAccountValues: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Organization", "model.Organization"),
					},
					Budget: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget", "model.Budget"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.Organization", "model.Organization"),
						},
						BudgetRevisions: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions", "model.BudgetRevision"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Organization", "model.Organization"),
							},
							Budget: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Budget", "model.Budget"),
							},
							BudgetRevisionAccountValues: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
							},
						},
						BudgetAccountValues: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues", "model.BudgetAccountValue"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Organization", "model.Organization"),
							},
							Budget: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Budget", "model.Budget"),
							},
							Account: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Account", "model.Account"),
							},
						},
					},
					BudgetRevision: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision", "model.BudgetRevision"),
					},
					Account: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Account", "model.Account"),
					},
				},
				BudgetAccountValues: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetAccountValues", "model.BudgetAccountValue"),
				},
				TransactionAssignments: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditLedgerAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitLedgerAccount struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments", "model.TransactionAssignment"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Organization", "model.Organization"),
					},
					Transaction: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditLedgerAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitLedgerAccount struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction", "model.Transaction_"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.Organization", "model.Organization"),
						},
						CreditLedgerAccount: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount", "model.LedgerAccount"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.Organization", "model.Organization"),
							},
							CreditTransactions: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.CreditTransactions", "model.Transaction_"),
							},
							DebitTransactions: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.DebitTransactions", "model.Transaction_"),
							},
						},
						DebitLedgerAccount: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.DebitLedgerAccount", "model.LedgerAccount"),
						},
						TransactionAssignments: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.TransactionAssignments", "model.TransactionAssignment"),
						},
					},
					Account: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Account", "model.Account"),
					},
				},
			},
		},
		AccountGroups: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.AccountGroups", "model.AccountGroup"),
		},
		Accounts: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.Accounts", "model.Account"),
		},
		BudgetRevisions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.BudgetRevisions", "model.BudgetRevision"),
		},
		BudgetRevisionAccountValues: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
		},
		BudgetAccountValues: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.BudgetAccountValues", "model.BudgetAccountValue"),
		},
		Budgets: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.Budgets", "model.Budget"),
		},
		LedgerYears: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Organization.LedgerYears", "model.LedgerYear"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.LedgerYears.Organization", "model.Organization"),
			},
		},
		LedgerAccounts: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.LedgerAccounts", "model.LedgerAccount"),
		},
		ReportTemplates: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Organization.ReportTemplates", "model.ReportTemplate"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.ReportTemplates.Organization", "model.Organization"),
			},
		},
		Reports: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Organization.Reports", "model.Report"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.Reports.Organization", "model.Organization"),
			},
		},
		Transactions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.Transactions", "model.Transaction_"),
		},
		TransactionAssignments: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.TransactionAssignments", "model.TransactionAssignment"),
		},
		Committees: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			PaymentAccounts struct {
				field.RelationField
				Committee struct {
					field.RelationField
				}
			}
			Submissions struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Committee struct {
					field.RelationField
				}
				CreatedBy struct {
					field.RelationField
					UserIdentities struct {
						field.RelationField
						User struct {
							field.RelationField
						}
					}
				}
			}
		}{
			RelationField: field.NewRelation("Organization.Committees", "model.Committee"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.Committees.Organization", "model.Organization"),
			},
			PaymentAccounts: struct {
				field.RelationField
				Committee struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Organization.Committees.PaymentAccounts", "model.CommitteePaymentAccount"),
				Committee: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.Committees.PaymentAccounts.Committee", "model.Committee"),
				},
			},
			Submissions: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Committee struct {
					field.RelationField
				}
				CreatedBy struct {
					field.RelationField
					UserIdentities struct {
						field.RelationField
						User struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("Organization.Committees.Submissions", "model.Submission"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.Committees.Submissions.Organization", "model.Organization"),
				},
				Committee: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.Committees.Submissions.Committee", "model.Committee"),
				},
				CreatedBy: struct {
					field.RelationField
					UserIdentities struct {
						field.RelationField
						User struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("Organization.Committees.Submissions.CreatedBy", "model.User"),
					UserIdentities: struct {
						field.RelationField
						User struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Organization.Committees.Submissions.CreatedBy.UserIdentities", "model.UserIdentity"),
						User: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.Committees.Submissions.CreatedBy.UserIdentities.User", "model.User"),
						},
					},
				},
			},
		},
		Submissions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.Submissions", "model.Submission"),
		},
	}

	_budgetAccountValue.Budget = budgetAccountValueBelongsToBudget{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Budget", "model.Budget"),
	}

	_budgetAccountValue.Account = budgetAccountValueBelongsToAccount{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Account", "model.Account"),
	}

	_budgetAccountValue.fillFieldMap()

	return _budgetAccountValue
}

type budgetAccountValue struct {
	budgetAccountValueDo budgetAccountValueDo

	ALL            field.Asterisk
	ID             field.Field
	CustomID       field.String
	OrganizationID field.Field
	BudgetID       field.Field
	AccountID      field.Field
	Value          field.Field
	UpdatedAt      field.Time
	CreatedAt      field.Time
	Organization   budgetAccountValueBelongsToOrganization

	Budget budgetAccountValueBelongsToBudget

	Account budgetAccountValueBelongsToAccount

	fieldMap map[string]field.Expr
}

func (b budgetAccountValue) Table(newTableName string) *budgetAccountValue {
	b.budgetAccountValueDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b budgetAccountValue) As(alias string) *budgetAccountValue {
	b.budgetAccountValueDo.DO = *(b.budgetAccountValueDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *budgetAccountValue) updateTableName(table string) *budgetAccountValue {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewField(table, "id")
	b.CustomID = field.NewString(table, "custom_id")
	b.OrganizationID = field.NewField(table, "organization_id")
	b.BudgetID = field.NewField(table, "budget_id")
	b.AccountID = field.NewField(table, "account_id")
	b.Value = field.NewField(table, "value")
	b.UpdatedAt = field.NewTime(table, "updated_at")
	b.CreatedAt = field.NewTime(table, "created_at")

	b.fillFieldMap()

	return b
}

func (b *budgetAccountValue) WithContext(ctx context.Context) IBudgetAccountValueDo {
	return b.budgetAccountValueDo.WithContext(ctx)
}

func (b budgetAccountValue) TableName() string { return b.budgetAccountValueDo.TableName() }

func (b budgetAccountValue) Alias() string { return b.budgetAccountValueDo.Alias() }

func (b budgetAccountValue) Columns(cols ...field.Expr) gen.Columns {
	return b.budgetAccountValueDo.Columns(cols...)
}

func (b *budgetAccountValue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *budgetAccountValue) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 11)
	b.fieldMap["id"] = b.ID
	b.fieldMap["custom_id"] = b.CustomID
	b.fieldMap["organization_id"] = b.OrganizationID
	b.fieldMap["budget_id"] = b.BudgetID
	b.fieldMap["account_id"] = b.AccountID
	b.fieldMap["value"] = b.Value
	b.fieldMap["updated_at"] = b.UpdatedAt
	b.fieldMap["created_at"] = b.CreatedAt

}

func (b budgetAccountValue) clone(db *gorm.DB) budgetAccountValue {
	b.budgetAccountValueDo.ReplaceConnPool(db.Statement.ConnPool)
	b.Organization.db = db.Session(&gorm.Session{Initialized: true})
	b.Organization.db.Statement.ConnPool = db.Statement.ConnPool
	b.Budget.db = db.Session(&gorm.Session{Initialized: true})
	b.Budget.db.Statement.ConnPool = db.Statement.ConnPool
	b.Account.db = db.Session(&gorm.Session{Initialized: true})
	b.Account.db.Statement.ConnPool = db.Statement.ConnPool
	return b
}

func (b budgetAccountValue) replaceDB(db *gorm.DB) budgetAccountValue {
	b.budgetAccountValueDo.ReplaceDB(db)
	b.Organization.db = db.Session(&gorm.Session{})
	b.Budget.db = db.Session(&gorm.Session{})
	b.Account.db = db.Session(&gorm.Session{})
	return b
}

type budgetAccountValueBelongsToOrganization struct {
	db *gorm.DB

	field.RelationField

	SubmissionSettings struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
	}
	AccountGroupAssignments struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
		AccountGroup struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroupAssignments struct {
				field.RelationField
			}
		}
		Account struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			ParentAccount struct {
				field.RelationField
			}
			ChildAccounts struct {
				field.RelationField
			}
			AccountGroupAssignments struct {
				field.RelationField
			}
			BudgetRevisionAccountValues struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Budget struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					BudgetRevisions struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
						}
						BudgetRevisionAccountValues struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
				}
				BudgetRevision struct {
					field.RelationField
				}
				Account struct {
					field.RelationField
				}
			}
			BudgetAccountValues struct {
				field.RelationField
			}
			TransactionAssignments struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Transaction struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					CreditLedgerAccount struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditTransactions struct {
							field.RelationField
						}
						DebitTransactions struct {
							field.RelationField
						}
					}
					DebitLedgerAccount struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
				}
			}
		}
	}
	AccountGroups struct {
		field.RelationField
	}
	Accounts struct {
		field.RelationField
	}
	BudgetRevisions struct {
		field.RelationField
	}
	BudgetRevisionAccountValues struct {
		field.RelationField
	}
	BudgetAccountValues struct {
		field.RelationField
	}
	Budgets struct {
		field.RelationField
	}
	LedgerYears struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
	}
	LedgerAccounts struct {
		field.RelationField
	}
	ReportTemplates struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
	}
	Reports struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
	}
	Transactions struct {
		field.RelationField
	}
	TransactionAssignments struct {
		field.RelationField
	}
	Committees struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
		PaymentAccounts struct {
			field.RelationField
			Committee struct {
				field.RelationField
			}
		}
		Submissions struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			Committee struct {
				field.RelationField
			}
			CreatedBy struct {
				field.RelationField
				UserIdentities struct {
					field.RelationField
					User struct {
						field.RelationField
					}
				}
			}
		}
	}
	Submissions struct {
		field.RelationField
	}
}

func (a budgetAccountValueBelongsToOrganization) Where(conds ...field.Expr) *budgetAccountValueBelongsToOrganization {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a budgetAccountValueBelongsToOrganization) WithContext(ctx context.Context) *budgetAccountValueBelongsToOrganization {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a budgetAccountValueBelongsToOrganization) Session(session *gorm.Session) *budgetAccountValueBelongsToOrganization {
	a.db = a.db.Session(session)
	return &a
}

func (a budgetAccountValueBelongsToOrganization) Model(m *model.BudgetAccountValue) *budgetAccountValueBelongsToOrganizationTx {
	return &budgetAccountValueBelongsToOrganizationTx{a.db.Model(m).Association(a.Name())}
}

func (a budgetAccountValueBelongsToOrganization) Unscoped() *budgetAccountValueBelongsToOrganization {
	a.db = a.db.Unscoped()
	return &a
}

type budgetAccountValueBelongsToOrganizationTx struct{ tx *gorm.Association }

func (a budgetAccountValueBelongsToOrganizationTx) Find() (result *model.Organization, err error) {
	return result, a.tx.Find(&result)
}

func (a budgetAccountValueBelongsToOrganizationTx) Append(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a budgetAccountValueBelongsToOrganizationTx) Replace(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a budgetAccountValueBelongsToOrganizationTx) Delete(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a budgetAccountValueBelongsToOrganizationTx) Clear() error {
	return a.tx.Clear()
}

func (a budgetAccountValueBelongsToOrganizationTx) Count() int64 {
	return a.tx.Count()
}

func (a budgetAccountValueBelongsToOrganizationTx) Unscoped() *budgetAccountValueBelongsToOrganizationTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type budgetAccountValueBelongsToBudget struct {
	db *gorm.DB

	field.RelationField
}

func (a budgetAccountValueBelongsToBudget) Where(conds ...field.Expr) *budgetAccountValueBelongsToBudget {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a budgetAccountValueBelongsToBudget) WithContext(ctx context.Context) *budgetAccountValueBelongsToBudget {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a budgetAccountValueBelongsToBudget) Session(session *gorm.Session) *budgetAccountValueBelongsToBudget {
	a.db = a.db.Session(session)
	return &a
}

func (a budgetAccountValueBelongsToBudget) Model(m *model.BudgetAccountValue) *budgetAccountValueBelongsToBudgetTx {
	return &budgetAccountValueBelongsToBudgetTx{a.db.Model(m).Association(a.Name())}
}

func (a budgetAccountValueBelongsToBudget) Unscoped() *budgetAccountValueBelongsToBudget {
	a.db = a.db.Unscoped()
	return &a
}

type budgetAccountValueBelongsToBudgetTx struct{ tx *gorm.Association }

func (a budgetAccountValueBelongsToBudgetTx) Find() (result *model.Budget, err error) {
	return result, a.tx.Find(&result)
}

func (a budgetAccountValueBelongsToBudgetTx) Append(values ...*model.Budget) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a budgetAccountValueBelongsToBudgetTx) Replace(values ...*model.Budget) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a budgetAccountValueBelongsToBudgetTx) Delete(values ...*model.Budget) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a budgetAccountValueBelongsToBudgetTx) Clear() error {
	return a.tx.Clear()
}

func (a budgetAccountValueBelongsToBudgetTx) Count() int64 {
	return a.tx.Count()
}

func (a budgetAccountValueBelongsToBudgetTx) Unscoped() *budgetAccountValueBelongsToBudgetTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type budgetAccountValueBelongsToAccount struct {
	db *gorm.DB

	field.RelationField
}

func (a budgetAccountValueBelongsToAccount) Where(conds ...field.Expr) *budgetAccountValueBelongsToAccount {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a budgetAccountValueBelongsToAccount) WithContext(ctx context.Context) *budgetAccountValueBelongsToAccount {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a budgetAccountValueBelongsToAccount) Session(session *gorm.Session) *budgetAccountValueBelongsToAccount {
	a.db = a.db.Session(session)
	return &a
}

func (a budgetAccountValueBelongsToAccount) Model(m *model.BudgetAccountValue) *budgetAccountValueBelongsToAccountTx {
	return &budgetAccountValueBelongsToAccountTx{a.db.Model(m).Association(a.Name())}
}

func (a budgetAccountValueBelongsToAccount) Unscoped() *budgetAccountValueBelongsToAccount {
	a.db = a.db.Unscoped()
	return &a
}

type budgetAccountValueBelongsToAccountTx struct{ tx *gorm.Association }

func (a budgetAccountValueBelongsToAccountTx) Find() (result *model.Account, err error) {
	return result, a.tx.Find(&result)
}

func (a budgetAccountValueBelongsToAccountTx) Append(values ...*model.Account) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a budgetAccountValueBelongsToAccountTx) Replace(values ...*model.Account) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a budgetAccountValueBelongsToAccountTx) Delete(values ...*model.Account) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a budgetAccountValueBelongsToAccountTx) Clear() error {
	return a.tx.Clear()
}

func (a budgetAccountValueBelongsToAccountTx) Count() int64 {
	return a.tx.Count()
}

func (a budgetAccountValueBelongsToAccountTx) Unscoped() *budgetAccountValueBelongsToAccountTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type budgetAccountValueDo struct{ gen.DO }

type IBudgetAccountValueDo interface {
	gen.SubQuery
	Debug() IBudgetAccountValueDo
	WithContext(ctx context.Context) IBudgetAccountValueDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBudgetAccountValueDo
	WriteDB() IBudgetAccountValueDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBudgetAccountValueDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBudgetAccountValueDo
	Not(conds ...gen.Condition) IBudgetAccountValueDo
	Or(conds ...gen.Condition) IBudgetAccountValueDo
	Select(conds ...field.Expr) IBudgetAccountValueDo
	Where(conds ...gen.Condition) IBudgetAccountValueDo
	Order(conds ...field.Expr) IBudgetAccountValueDo
	Distinct(cols ...field.Expr) IBudgetAccountValueDo
	Omit(cols ...field.Expr) IBudgetAccountValueDo
	Join(table schema.Tabler, on ...field.Expr) IBudgetAccountValueDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBudgetAccountValueDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBudgetAccountValueDo
	Group(cols ...field.Expr) IBudgetAccountValueDo
	Having(conds ...gen.Condition) IBudgetAccountValueDo
	Limit(limit int) IBudgetAccountValueDo
	Offset(offset int) IBudgetAccountValueDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBudgetAccountValueDo
	Unscoped() IBudgetAccountValueDo
	Create(values ...*model.BudgetAccountValue) error
	CreateInBatches(values []*model.BudgetAccountValue, batchSize int) error
	Save(values ...*model.BudgetAccountValue) error
	First() (*model.BudgetAccountValue, error)
	Take() (*model.BudgetAccountValue, error)
	Last() (*model.BudgetAccountValue, error)
	Find() ([]*model.BudgetAccountValue, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BudgetAccountValue, err error)
	FindInBatches(result *[]*model.BudgetAccountValue, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BudgetAccountValue) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBudgetAccountValueDo
	Assign(attrs ...field.AssignExpr) IBudgetAccountValueDo
	Joins(fields ...field.RelationField) IBudgetAccountValueDo
	Preload(fields ...field.RelationField) IBudgetAccountValueDo
	FirstOrInit() (*model.BudgetAccountValue, error)
	FirstOrCreate() (*model.BudgetAccountValue, error)
	FindByPage(offset int, limit int) (result []*model.BudgetAccountValue, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBudgetAccountValueDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b budgetAccountValueDo) Debug() IBudgetAccountValueDo {
	return b.withDO(b.DO.Debug())
}

func (b budgetAccountValueDo) WithContext(ctx context.Context) IBudgetAccountValueDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b budgetAccountValueDo) ReadDB() IBudgetAccountValueDo {
	return b.Clauses(dbresolver.Read)
}

func (b budgetAccountValueDo) WriteDB() IBudgetAccountValueDo {
	return b.Clauses(dbresolver.Write)
}

func (b budgetAccountValueDo) Session(config *gorm.Session) IBudgetAccountValueDo {
	return b.withDO(b.DO.Session(config))
}

func (b budgetAccountValueDo) Clauses(conds ...clause.Expression) IBudgetAccountValueDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b budgetAccountValueDo) Returning(value interface{}, columns ...string) IBudgetAccountValueDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b budgetAccountValueDo) Not(conds ...gen.Condition) IBudgetAccountValueDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b budgetAccountValueDo) Or(conds ...gen.Condition) IBudgetAccountValueDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b budgetAccountValueDo) Select(conds ...field.Expr) IBudgetAccountValueDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b budgetAccountValueDo) Where(conds ...gen.Condition) IBudgetAccountValueDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b budgetAccountValueDo) Order(conds ...field.Expr) IBudgetAccountValueDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b budgetAccountValueDo) Distinct(cols ...field.Expr) IBudgetAccountValueDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b budgetAccountValueDo) Omit(cols ...field.Expr) IBudgetAccountValueDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b budgetAccountValueDo) Join(table schema.Tabler, on ...field.Expr) IBudgetAccountValueDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b budgetAccountValueDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBudgetAccountValueDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b budgetAccountValueDo) RightJoin(table schema.Tabler, on ...field.Expr) IBudgetAccountValueDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b budgetAccountValueDo) Group(cols ...field.Expr) IBudgetAccountValueDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b budgetAccountValueDo) Having(conds ...gen.Condition) IBudgetAccountValueDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b budgetAccountValueDo) Limit(limit int) IBudgetAccountValueDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b budgetAccountValueDo) Offset(offset int) IBudgetAccountValueDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b budgetAccountValueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBudgetAccountValueDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b budgetAccountValueDo) Unscoped() IBudgetAccountValueDo {
	return b.withDO(b.DO.Unscoped())
}

func (b budgetAccountValueDo) Create(values ...*model.BudgetAccountValue) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b budgetAccountValueDo) CreateInBatches(values []*model.BudgetAccountValue, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b budgetAccountValueDo) Save(values ...*model.BudgetAccountValue) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b budgetAccountValueDo) First() (*model.BudgetAccountValue, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BudgetAccountValue), nil
	}
}

func (b budgetAccountValueDo) Take() (*model.BudgetAccountValue, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BudgetAccountValue), nil
	}
}

func (b budgetAccountValueDo) Last() (*model.BudgetAccountValue, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BudgetAccountValue), nil
	}
}

func (b budgetAccountValueDo) Find() ([]*model.BudgetAccountValue, error) {
	result, err := b.DO.Find()
	return result.([]*model.BudgetAccountValue), err
}

func (b budgetAccountValueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BudgetAccountValue, err error) {
	buf := make([]*model.BudgetAccountValue, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b budgetAccountValueDo) FindInBatches(result *[]*model.BudgetAccountValue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b budgetAccountValueDo) Attrs(attrs ...field.AssignExpr) IBudgetAccountValueDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b budgetAccountValueDo) Assign(attrs ...field.AssignExpr) IBudgetAccountValueDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b budgetAccountValueDo) Joins(fields ...field.RelationField) IBudgetAccountValueDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b budgetAccountValueDo) Preload(fields ...field.RelationField) IBudgetAccountValueDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b budgetAccountValueDo) FirstOrInit() (*model.BudgetAccountValue, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BudgetAccountValue), nil
	}
}

func (b budgetAccountValueDo) FirstOrCreate() (*model.BudgetAccountValue, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BudgetAccountValue), nil
	}
}

func (b budgetAccountValueDo) FindByPage(offset int, limit int) (result []*model.BudgetAccountValue, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b budgetAccountValueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b budgetAccountValueDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b budgetAccountValueDo) Delete(models ...*model.BudgetAccountValue) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *budgetAccountValueDo) withDO(do gen.Dao) *budgetAccountValueDo {
	b.DO = *do.(*gen.DO)
	return b
}
