// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"github.com/pixlcrashr/vsfv/pkg/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newCommitteePaymentAccount(db *gorm.DB, opts ...gen.DOOption) committeePaymentAccount {
	_committeePaymentAccount := committeePaymentAccount{}

	_committeePaymentAccount.committeePaymentAccountDo.UseDB(db, opts...)
	_committeePaymentAccount.committeePaymentAccountDo.UseModel(&model.CommitteePaymentAccount{})

	tableName := _committeePaymentAccount.committeePaymentAccountDo.TableName()
	_committeePaymentAccount.ALL = field.NewAsterisk(tableName)
	_committeePaymentAccount.ID = field.NewField(tableName, "id")
	_committeePaymentAccount.CommitteeID = field.NewField(tableName, "committee_id")
	_committeePaymentAccount.Kind = field.NewInt(tableName, "kind")
	_committeePaymentAccount.DisplayLabel = field.NewString(tableName, "display_label")
	_committeePaymentAccount.CreatedAt = field.NewTime(tableName, "created_at")
	_committeePaymentAccount.Committee = committeePaymentAccountBelongsToCommittee{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Committee", "model.Committee"),
		Organization: struct {
			field.RelationField
			SubmissionSettings struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			AccountGroupAssignments struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
				}
			}
			AccountGroups struct {
				field.RelationField
			}
			Accounts struct {
				field.RelationField
			}
			BudgetRevisions struct {
				field.RelationField
			}
			BudgetRevisionAccountValues struct {
				field.RelationField
			}
			BudgetAccountValues struct {
				field.RelationField
			}
			Budgets struct {
				field.RelationField
			}
			LedgerYears struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			LedgerAccounts struct {
				field.RelationField
			}
			ReportTemplates struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Reports struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Transactions struct {
				field.RelationField
			}
			TransactionAssignments struct {
				field.RelationField
			}
			Committees struct {
				field.RelationField
			}
			Submissions struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Committee struct {
					field.RelationField
				}
				CreatedBy struct {
					field.RelationField
					UserIdentities struct {
						field.RelationField
						User struct {
							field.RelationField
						}
					}
				}
			}
		}{
			RelationField: field.NewRelation("Committee.Organization", "model.Organization"),
			SubmissionSettings: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Committee.Organization.SubmissionSettings", "model.OrganizationSubmissionSettings"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Committee.Organization.SubmissionSettings.Organization", "model.Organization"),
				},
			},
			AccountGroupAssignments: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments", "model.AccountGroupAssignment"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Organization", "model.Organization"),
				},
				AccountGroup: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.AccountGroup", "model.AccountGroup"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.AccountGroup.Organization", "model.Organization"),
					},
					AccountGroupAssignments: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.AccountGroup.AccountGroupAssignments", "model.AccountGroupAssignment"),
					},
				},
				Account: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account", "model.Account"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.Organization", "model.Organization"),
					},
					ParentAccount: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.ParentAccount", "model.Account"),
					},
					ChildAccounts: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.ChildAccounts", "model.Account"),
					},
					AccountGroupAssignments: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.AccountGroupAssignments", "model.AccountGroupAssignment"),
					},
					BudgetRevisionAccountValues: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Organization", "model.Organization"),
						},
						Budget: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}{
							RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget", "model.Budget"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.Organization", "model.Organization"),
							},
							BudgetRevisions: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions", "model.BudgetRevision"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Organization", "model.Organization"),
								},
								Budget: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Budget", "model.Budget"),
								},
								BudgetRevisionAccountValues: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
								},
							},
							BudgetAccountValues: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues", "model.BudgetAccountValue"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Organization", "model.Organization"),
								},
								Budget: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Budget", "model.Budget"),
								},
								Account: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Account", "model.Account"),
								},
							},
						},
						BudgetRevision: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision", "model.BudgetRevision"),
						},
						Account: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Account", "model.Account"),
						},
					},
					BudgetAccountValues: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.BudgetAccountValues", "model.BudgetAccountValue"),
					},
					TransactionAssignments: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.TransactionAssignments", "model.TransactionAssignment"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.TransactionAssignments.Organization", "model.Organization"),
						},
						Transaction: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction", "model.Transaction_"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.Organization", "model.Organization"),
							},
							CreditLedgerAccount: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount", "model.LedgerAccount"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.Organization", "model.Organization"),
								},
								CreditTransactions: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.CreditTransactions", "model.Transaction_"),
								},
								DebitTransactions: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.DebitTransactions", "model.Transaction_"),
								},
							},
							DebitLedgerAccount: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.DebitLedgerAccount", "model.LedgerAccount"),
							},
							TransactionAssignments: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.TransactionAssignments", "model.TransactionAssignment"),
							},
						},
						Account: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Committee.Organization.AccountGroupAssignments.Account.TransactionAssignments.Account", "model.Account"),
						},
					},
				},
			},
			AccountGroups: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Committee.Organization.AccountGroups", "model.AccountGroup"),
			},
			Accounts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Committee.Organization.Accounts", "model.Account"),
			},
			BudgetRevisions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Committee.Organization.BudgetRevisions", "model.BudgetRevision"),
			},
			BudgetRevisionAccountValues: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Committee.Organization.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
			},
			BudgetAccountValues: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Committee.Organization.BudgetAccountValues", "model.BudgetAccountValue"),
			},
			Budgets: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Committee.Organization.Budgets", "model.Budget"),
			},
			LedgerYears: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Committee.Organization.LedgerYears", "model.LedgerYear"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Committee.Organization.LedgerYears.Organization", "model.Organization"),
				},
			},
			LedgerAccounts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Committee.Organization.LedgerAccounts", "model.LedgerAccount"),
			},
			ReportTemplates: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Committee.Organization.ReportTemplates", "model.ReportTemplate"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Committee.Organization.ReportTemplates.Organization", "model.Organization"),
				},
			},
			Reports: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Committee.Organization.Reports", "model.Report"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Committee.Organization.Reports.Organization", "model.Organization"),
				},
			},
			Transactions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Committee.Organization.Transactions", "model.Transaction_"),
			},
			TransactionAssignments: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Committee.Organization.TransactionAssignments", "model.TransactionAssignment"),
			},
			Committees: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Committee.Organization.Committees", "model.Committee"),
			},
			Submissions: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Committee struct {
					field.RelationField
				}
				CreatedBy struct {
					field.RelationField
					UserIdentities struct {
						field.RelationField
						User struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("Committee.Organization.Submissions", "model.Submission"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Committee.Organization.Submissions.Organization", "model.Organization"),
				},
				Committee: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Committee.Organization.Submissions.Committee", "model.Committee"),
				},
				CreatedBy: struct {
					field.RelationField
					UserIdentities struct {
						field.RelationField
						User struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("Committee.Organization.Submissions.CreatedBy", "model.User"),
					UserIdentities: struct {
						field.RelationField
						User struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Committee.Organization.Submissions.CreatedBy.UserIdentities", "model.UserIdentity"),
						User: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Committee.Organization.Submissions.CreatedBy.UserIdentities.User", "model.User"),
						},
					},
				},
			},
		},
		PaymentAccounts: struct {
			field.RelationField
			Committee struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Committee.PaymentAccounts", "model.CommitteePaymentAccount"),
			Committee: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Committee.PaymentAccounts.Committee", "model.Committee"),
			},
		},
		Submissions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Committee.Submissions", "model.Submission"),
		},
	}

	_committeePaymentAccount.fillFieldMap()

	return _committeePaymentAccount
}

type committeePaymentAccount struct {
	committeePaymentAccountDo committeePaymentAccountDo

	ALL          field.Asterisk
	ID           field.Field
	CommitteeID  field.Field
	Kind         field.Int
	DisplayLabel field.String
	CreatedAt    field.Time
	Committee    committeePaymentAccountBelongsToCommittee

	fieldMap map[string]field.Expr
}

func (c committeePaymentAccount) Table(newTableName string) *committeePaymentAccount {
	c.committeePaymentAccountDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c committeePaymentAccount) As(alias string) *committeePaymentAccount {
	c.committeePaymentAccountDo.DO = *(c.committeePaymentAccountDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *committeePaymentAccount) updateTableName(table string) *committeePaymentAccount {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewField(table, "id")
	c.CommitteeID = field.NewField(table, "committee_id")
	c.Kind = field.NewInt(table, "kind")
	c.DisplayLabel = field.NewString(table, "display_label")
	c.CreatedAt = field.NewTime(table, "created_at")

	c.fillFieldMap()

	return c
}

func (c *committeePaymentAccount) WithContext(ctx context.Context) ICommitteePaymentAccountDo {
	return c.committeePaymentAccountDo.WithContext(ctx)
}

func (c committeePaymentAccount) TableName() string { return c.committeePaymentAccountDo.TableName() }

func (c committeePaymentAccount) Alias() string { return c.committeePaymentAccountDo.Alias() }

func (c committeePaymentAccount) Columns(cols ...field.Expr) gen.Columns {
	return c.committeePaymentAccountDo.Columns(cols...)
}

func (c *committeePaymentAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *committeePaymentAccount) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["id"] = c.ID
	c.fieldMap["committee_id"] = c.CommitteeID
	c.fieldMap["kind"] = c.Kind
	c.fieldMap["display_label"] = c.DisplayLabel
	c.fieldMap["created_at"] = c.CreatedAt

}

func (c committeePaymentAccount) clone(db *gorm.DB) committeePaymentAccount {
	c.committeePaymentAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	c.Committee.db = db.Session(&gorm.Session{Initialized: true})
	c.Committee.db.Statement.ConnPool = db.Statement.ConnPool
	return c
}

func (c committeePaymentAccount) replaceDB(db *gorm.DB) committeePaymentAccount {
	c.committeePaymentAccountDo.ReplaceDB(db)
	c.Committee.db = db.Session(&gorm.Session{})
	return c
}

type committeePaymentAccountBelongsToCommittee struct {
	db *gorm.DB

	field.RelationField

	Organization struct {
		field.RelationField
		SubmissionSettings struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		AccountGroupAssignments struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroup struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}
			Account struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
				BudgetAccountValues struct {
					field.RelationField
				}
				TransactionAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditLedgerAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitLedgerAccount struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
			}
		}
		AccountGroups struct {
			field.RelationField
		}
		Accounts struct {
			field.RelationField
		}
		BudgetRevisions struct {
			field.RelationField
		}
		BudgetRevisionAccountValues struct {
			field.RelationField
		}
		BudgetAccountValues struct {
			field.RelationField
		}
		Budgets struct {
			field.RelationField
		}
		LedgerYears struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		LedgerAccounts struct {
			field.RelationField
		}
		ReportTemplates struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Reports struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Transactions struct {
			field.RelationField
		}
		TransactionAssignments struct {
			field.RelationField
		}
		Committees struct {
			field.RelationField
		}
		Submissions struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			Committee struct {
				field.RelationField
			}
			CreatedBy struct {
				field.RelationField
				UserIdentities struct {
					field.RelationField
					User struct {
						field.RelationField
					}
				}
			}
		}
	}
	PaymentAccounts struct {
		field.RelationField
		Committee struct {
			field.RelationField
		}
	}
	Submissions struct {
		field.RelationField
	}
}

func (a committeePaymentAccountBelongsToCommittee) Where(conds ...field.Expr) *committeePaymentAccountBelongsToCommittee {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a committeePaymentAccountBelongsToCommittee) WithContext(ctx context.Context) *committeePaymentAccountBelongsToCommittee {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a committeePaymentAccountBelongsToCommittee) Session(session *gorm.Session) *committeePaymentAccountBelongsToCommittee {
	a.db = a.db.Session(session)
	return &a
}

func (a committeePaymentAccountBelongsToCommittee) Model(m *model.CommitteePaymentAccount) *committeePaymentAccountBelongsToCommitteeTx {
	return &committeePaymentAccountBelongsToCommitteeTx{a.db.Model(m).Association(a.Name())}
}

func (a committeePaymentAccountBelongsToCommittee) Unscoped() *committeePaymentAccountBelongsToCommittee {
	a.db = a.db.Unscoped()
	return &a
}

type committeePaymentAccountBelongsToCommitteeTx struct{ tx *gorm.Association }

func (a committeePaymentAccountBelongsToCommitteeTx) Find() (result *model.Committee, err error) {
	return result, a.tx.Find(&result)
}

func (a committeePaymentAccountBelongsToCommitteeTx) Append(values ...*model.Committee) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a committeePaymentAccountBelongsToCommitteeTx) Replace(values ...*model.Committee) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a committeePaymentAccountBelongsToCommitteeTx) Delete(values ...*model.Committee) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a committeePaymentAccountBelongsToCommitteeTx) Clear() error {
	return a.tx.Clear()
}

func (a committeePaymentAccountBelongsToCommitteeTx) Count() int64 {
	return a.tx.Count()
}

func (a committeePaymentAccountBelongsToCommitteeTx) Unscoped() *committeePaymentAccountBelongsToCommitteeTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type committeePaymentAccountDo struct{ gen.DO }

type ICommitteePaymentAccountDo interface {
	gen.SubQuery
	Debug() ICommitteePaymentAccountDo
	WithContext(ctx context.Context) ICommitteePaymentAccountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICommitteePaymentAccountDo
	WriteDB() ICommitteePaymentAccountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICommitteePaymentAccountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICommitteePaymentAccountDo
	Not(conds ...gen.Condition) ICommitteePaymentAccountDo
	Or(conds ...gen.Condition) ICommitteePaymentAccountDo
	Select(conds ...field.Expr) ICommitteePaymentAccountDo
	Where(conds ...gen.Condition) ICommitteePaymentAccountDo
	Order(conds ...field.Expr) ICommitteePaymentAccountDo
	Distinct(cols ...field.Expr) ICommitteePaymentAccountDo
	Omit(cols ...field.Expr) ICommitteePaymentAccountDo
	Join(table schema.Tabler, on ...field.Expr) ICommitteePaymentAccountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICommitteePaymentAccountDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICommitteePaymentAccountDo
	Group(cols ...field.Expr) ICommitteePaymentAccountDo
	Having(conds ...gen.Condition) ICommitteePaymentAccountDo
	Limit(limit int) ICommitteePaymentAccountDo
	Offset(offset int) ICommitteePaymentAccountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICommitteePaymentAccountDo
	Unscoped() ICommitteePaymentAccountDo
	Create(values ...*model.CommitteePaymentAccount) error
	CreateInBatches(values []*model.CommitteePaymentAccount, batchSize int) error
	Save(values ...*model.CommitteePaymentAccount) error
	First() (*model.CommitteePaymentAccount, error)
	Take() (*model.CommitteePaymentAccount, error)
	Last() (*model.CommitteePaymentAccount, error)
	Find() ([]*model.CommitteePaymentAccount, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CommitteePaymentAccount, err error)
	FindInBatches(result *[]*model.CommitteePaymentAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CommitteePaymentAccount) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICommitteePaymentAccountDo
	Assign(attrs ...field.AssignExpr) ICommitteePaymentAccountDo
	Joins(fields ...field.RelationField) ICommitteePaymentAccountDo
	Preload(fields ...field.RelationField) ICommitteePaymentAccountDo
	FirstOrInit() (*model.CommitteePaymentAccount, error)
	FirstOrCreate() (*model.CommitteePaymentAccount, error)
	FindByPage(offset int, limit int) (result []*model.CommitteePaymentAccount, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICommitteePaymentAccountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c committeePaymentAccountDo) Debug() ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Debug())
}

func (c committeePaymentAccountDo) WithContext(ctx context.Context) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c committeePaymentAccountDo) ReadDB() ICommitteePaymentAccountDo {
	return c.Clauses(dbresolver.Read)
}

func (c committeePaymentAccountDo) WriteDB() ICommitteePaymentAccountDo {
	return c.Clauses(dbresolver.Write)
}

func (c committeePaymentAccountDo) Session(config *gorm.Session) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Session(config))
}

func (c committeePaymentAccountDo) Clauses(conds ...clause.Expression) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c committeePaymentAccountDo) Returning(value interface{}, columns ...string) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c committeePaymentAccountDo) Not(conds ...gen.Condition) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c committeePaymentAccountDo) Or(conds ...gen.Condition) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c committeePaymentAccountDo) Select(conds ...field.Expr) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c committeePaymentAccountDo) Where(conds ...gen.Condition) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c committeePaymentAccountDo) Order(conds ...field.Expr) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c committeePaymentAccountDo) Distinct(cols ...field.Expr) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c committeePaymentAccountDo) Omit(cols ...field.Expr) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c committeePaymentAccountDo) Join(table schema.Tabler, on ...field.Expr) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c committeePaymentAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c committeePaymentAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c committeePaymentAccountDo) Group(cols ...field.Expr) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c committeePaymentAccountDo) Having(conds ...gen.Condition) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c committeePaymentAccountDo) Limit(limit int) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c committeePaymentAccountDo) Offset(offset int) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c committeePaymentAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c committeePaymentAccountDo) Unscoped() ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Unscoped())
}

func (c committeePaymentAccountDo) Create(values ...*model.CommitteePaymentAccount) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c committeePaymentAccountDo) CreateInBatches(values []*model.CommitteePaymentAccount, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c committeePaymentAccountDo) Save(values ...*model.CommitteePaymentAccount) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c committeePaymentAccountDo) First() (*model.CommitteePaymentAccount, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommitteePaymentAccount), nil
	}
}

func (c committeePaymentAccountDo) Take() (*model.CommitteePaymentAccount, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommitteePaymentAccount), nil
	}
}

func (c committeePaymentAccountDo) Last() (*model.CommitteePaymentAccount, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommitteePaymentAccount), nil
	}
}

func (c committeePaymentAccountDo) Find() ([]*model.CommitteePaymentAccount, error) {
	result, err := c.DO.Find()
	return result.([]*model.CommitteePaymentAccount), err
}

func (c committeePaymentAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CommitteePaymentAccount, err error) {
	buf := make([]*model.CommitteePaymentAccount, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c committeePaymentAccountDo) FindInBatches(result *[]*model.CommitteePaymentAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c committeePaymentAccountDo) Attrs(attrs ...field.AssignExpr) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c committeePaymentAccountDo) Assign(attrs ...field.AssignExpr) ICommitteePaymentAccountDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c committeePaymentAccountDo) Joins(fields ...field.RelationField) ICommitteePaymentAccountDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c committeePaymentAccountDo) Preload(fields ...field.RelationField) ICommitteePaymentAccountDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c committeePaymentAccountDo) FirstOrInit() (*model.CommitteePaymentAccount, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommitteePaymentAccount), nil
	}
}

func (c committeePaymentAccountDo) FirstOrCreate() (*model.CommitteePaymentAccount, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommitteePaymentAccount), nil
	}
}

func (c committeePaymentAccountDo) FindByPage(offset int, limit int) (result []*model.CommitteePaymentAccount, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c committeePaymentAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c committeePaymentAccountDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c committeePaymentAccountDo) Delete(models ...*model.CommitteePaymentAccount) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *committeePaymentAccountDo) withDO(do gen.Dao) *committeePaymentAccountDo {
	c.DO = *do.(*gen.DO)
	return c
}
