// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                          = new(Query)
	Account                    *account
	AccountGroup               *accountGroup
	AccountGroupAssignment     *accountGroupAssignment
	AuditLogEntry              *auditLogEntry
	AuthSession                *authSession
	Budget                     *budget
	BudgetAccountValue         *budgetAccountValue
	BudgetRevision             *budgetRevision
	BudgetRevisionAccountValue *budgetRevisionAccountValue
	CasbinRule                 *casbinRule
	LedgerAccount              *ledgerAccount
	LedgerYear                 *ledgerYear
	OAuth2Client               *oAuth2Client
	OAuth2Token                *oAuth2Token
	Organization               *organization
	Report                     *report
	ReportTemplate             *reportTemplate
	TransactionAssignment      *transactionAssignment
	Transaction_               *transaction_
	User                       *user
	UserGroup                  *userGroup
	UserIdentity               *userIdentity
	UserSettings               *userSettings
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Account = &Q.Account
	AccountGroup = &Q.AccountGroup
	AccountGroupAssignment = &Q.AccountGroupAssignment
	AuditLogEntry = &Q.AuditLogEntry
	AuthSession = &Q.AuthSession
	Budget = &Q.Budget
	BudgetAccountValue = &Q.BudgetAccountValue
	BudgetRevision = &Q.BudgetRevision
	BudgetRevisionAccountValue = &Q.BudgetRevisionAccountValue
	CasbinRule = &Q.CasbinRule
	LedgerAccount = &Q.LedgerAccount
	LedgerYear = &Q.LedgerYear
	OAuth2Client = &Q.OAuth2Client
	OAuth2Token = &Q.OAuth2Token
	Organization = &Q.Organization
	Report = &Q.Report
	ReportTemplate = &Q.ReportTemplate
	TransactionAssignment = &Q.TransactionAssignment
	Transaction_ = &Q.Transaction_
	User = &Q.User
	UserGroup = &Q.UserGroup
	UserIdentity = &Q.UserIdentity
	UserSettings = &Q.UserSettings
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                         db,
		Account:                    newAccount(db, opts...),
		AccountGroup:               newAccountGroup(db, opts...),
		AccountGroupAssignment:     newAccountGroupAssignment(db, opts...),
		AuditLogEntry:              newAuditLogEntry(db, opts...),
		AuthSession:                newAuthSession(db, opts...),
		Budget:                     newBudget(db, opts...),
		BudgetAccountValue:         newBudgetAccountValue(db, opts...),
		BudgetRevision:             newBudgetRevision(db, opts...),
		BudgetRevisionAccountValue: newBudgetRevisionAccountValue(db, opts...),
		CasbinRule:                 newCasbinRule(db, opts...),
		LedgerAccount:              newLedgerAccount(db, opts...),
		LedgerYear:                 newLedgerYear(db, opts...),
		OAuth2Client:               newOAuth2Client(db, opts...),
		OAuth2Token:                newOAuth2Token(db, opts...),
		Organization:               newOrganization(db, opts...),
		Report:                     newReport(db, opts...),
		ReportTemplate:             newReportTemplate(db, opts...),
		TransactionAssignment:      newTransactionAssignment(db, opts...),
		Transaction_:               newTransaction_(db, opts...),
		User:                       newUser(db, opts...),
		UserGroup:                  newUserGroup(db, opts...),
		UserIdentity:               newUserIdentity(db, opts...),
		UserSettings:               newUserSettings(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Account                    account
	AccountGroup               accountGroup
	AccountGroupAssignment     accountGroupAssignment
	AuditLogEntry              auditLogEntry
	AuthSession                authSession
	Budget                     budget
	BudgetAccountValue         budgetAccountValue
	BudgetRevision             budgetRevision
	BudgetRevisionAccountValue budgetRevisionAccountValue
	CasbinRule                 casbinRule
	LedgerAccount              ledgerAccount
	LedgerYear                 ledgerYear
	OAuth2Client               oAuth2Client
	OAuth2Token                oAuth2Token
	Organization               organization
	Report                     report
	ReportTemplate             reportTemplate
	TransactionAssignment      transactionAssignment
	Transaction_               transaction_
	User                       user
	UserGroup                  userGroup
	UserIdentity               userIdentity
	UserSettings               userSettings
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                         db,
		Account:                    q.Account.clone(db),
		AccountGroup:               q.AccountGroup.clone(db),
		AccountGroupAssignment:     q.AccountGroupAssignment.clone(db),
		AuditLogEntry:              q.AuditLogEntry.clone(db),
		AuthSession:                q.AuthSession.clone(db),
		Budget:                     q.Budget.clone(db),
		BudgetAccountValue:         q.BudgetAccountValue.clone(db),
		BudgetRevision:             q.BudgetRevision.clone(db),
		BudgetRevisionAccountValue: q.BudgetRevisionAccountValue.clone(db),
		CasbinRule:                 q.CasbinRule.clone(db),
		LedgerAccount:              q.LedgerAccount.clone(db),
		LedgerYear:                 q.LedgerYear.clone(db),
		OAuth2Client:               q.OAuth2Client.clone(db),
		OAuth2Token:                q.OAuth2Token.clone(db),
		Organization:               q.Organization.clone(db),
		Report:                     q.Report.clone(db),
		ReportTemplate:             q.ReportTemplate.clone(db),
		TransactionAssignment:      q.TransactionAssignment.clone(db),
		Transaction_:               q.Transaction_.clone(db),
		User:                       q.User.clone(db),
		UserGroup:                  q.UserGroup.clone(db),
		UserIdentity:               q.UserIdentity.clone(db),
		UserSettings:               q.UserSettings.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                         db,
		Account:                    q.Account.replaceDB(db),
		AccountGroup:               q.AccountGroup.replaceDB(db),
		AccountGroupAssignment:     q.AccountGroupAssignment.replaceDB(db),
		AuditLogEntry:              q.AuditLogEntry.replaceDB(db),
		AuthSession:                q.AuthSession.replaceDB(db),
		Budget:                     q.Budget.replaceDB(db),
		BudgetAccountValue:         q.BudgetAccountValue.replaceDB(db),
		BudgetRevision:             q.BudgetRevision.replaceDB(db),
		BudgetRevisionAccountValue: q.BudgetRevisionAccountValue.replaceDB(db),
		CasbinRule:                 q.CasbinRule.replaceDB(db),
		LedgerAccount:              q.LedgerAccount.replaceDB(db),
		LedgerYear:                 q.LedgerYear.replaceDB(db),
		OAuth2Client:               q.OAuth2Client.replaceDB(db),
		OAuth2Token:                q.OAuth2Token.replaceDB(db),
		Organization:               q.Organization.replaceDB(db),
		Report:                     q.Report.replaceDB(db),
		ReportTemplate:             q.ReportTemplate.replaceDB(db),
		TransactionAssignment:      q.TransactionAssignment.replaceDB(db),
		Transaction_:               q.Transaction_.replaceDB(db),
		User:                       q.User.replaceDB(db),
		UserGroup:                  q.UserGroup.replaceDB(db),
		UserIdentity:               q.UserIdentity.replaceDB(db),
		UserSettings:               q.UserSettings.replaceDB(db),
	}
}

type queryCtx struct {
	Account                    IAccountDo
	AccountGroup               IAccountGroupDo
	AccountGroupAssignment     IAccountGroupAssignmentDo
	AuditLogEntry              IAuditLogEntryDo
	AuthSession                IAuthSessionDo
	Budget                     IBudgetDo
	BudgetAccountValue         IBudgetAccountValueDo
	BudgetRevision             IBudgetRevisionDo
	BudgetRevisionAccountValue IBudgetRevisionAccountValueDo
	CasbinRule                 ICasbinRuleDo
	LedgerAccount              ILedgerAccountDo
	LedgerYear                 ILedgerYearDo
	OAuth2Client               IOAuth2ClientDo
	OAuth2Token                IOAuth2TokenDo
	Organization               IOrganizationDo
	Report                     IReportDo
	ReportTemplate             IReportTemplateDo
	TransactionAssignment      ITransactionAssignmentDo
	Transaction_               ITransaction_Do
	User                       IUserDo
	UserGroup                  IUserGroupDo
	UserIdentity               IUserIdentityDo
	UserSettings               IUserSettingsDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Account:                    q.Account.WithContext(ctx),
		AccountGroup:               q.AccountGroup.WithContext(ctx),
		AccountGroupAssignment:     q.AccountGroupAssignment.WithContext(ctx),
		AuditLogEntry:              q.AuditLogEntry.WithContext(ctx),
		AuthSession:                q.AuthSession.WithContext(ctx),
		Budget:                     q.Budget.WithContext(ctx),
		BudgetAccountValue:         q.BudgetAccountValue.WithContext(ctx),
		BudgetRevision:             q.BudgetRevision.WithContext(ctx),
		BudgetRevisionAccountValue: q.BudgetRevisionAccountValue.WithContext(ctx),
		CasbinRule:                 q.CasbinRule.WithContext(ctx),
		LedgerAccount:              q.LedgerAccount.WithContext(ctx),
		LedgerYear:                 q.LedgerYear.WithContext(ctx),
		OAuth2Client:               q.OAuth2Client.WithContext(ctx),
		OAuth2Token:                q.OAuth2Token.WithContext(ctx),
		Organization:               q.Organization.WithContext(ctx),
		Report:                     q.Report.WithContext(ctx),
		ReportTemplate:             q.ReportTemplate.WithContext(ctx),
		TransactionAssignment:      q.TransactionAssignment.WithContext(ctx),
		Transaction_:               q.Transaction_.WithContext(ctx),
		User:                       q.User.WithContext(ctx),
		UserGroup:                  q.UserGroup.WithContext(ctx),
		UserIdentity:               q.UserIdentity.WithContext(ctx),
		UserSettings:               q.UserSettings.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
