// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"github.com/pixlcrashr/vsfv/pkg/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newLedgerAccount(db *gorm.DB, opts ...gen.DOOption) ledgerAccount {
	_ledgerAccount := ledgerAccount{}

	_ledgerAccount.ledgerAccountDo.UseDB(db, opts...)
	_ledgerAccount.ledgerAccountDo.UseModel(&model.LedgerAccount{})

	tableName := _ledgerAccount.ledgerAccountDo.TableName()
	_ledgerAccount.ALL = field.NewAsterisk(tableName)
	_ledgerAccount.ID = field.NewField(tableName, "id")
	_ledgerAccount.CustomID = field.NewString(tableName, "custom_id")
	_ledgerAccount.OrganizationID = field.NewField(tableName, "organization_id")
	_ledgerAccount.Code = field.NewString(tableName, "code")
	_ledgerAccount.AccountType = field.NewInt(tableName, "account_type")
	_ledgerAccount.DisplayName = field.NewString(tableName, "display_name")
	_ledgerAccount.DisplayDescription = field.NewString(tableName, "display_description")
	_ledgerAccount.UpdatedAt = field.NewTime(tableName, "updated_at")
	_ledgerAccount.CreatedAt = field.NewTime(tableName, "created_at")
	_ledgerAccount.CreditTransactions = ledgerAccountHasManyCreditTransactions{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("CreditTransactions", "model.Transaction_"),
		Organization: struct {
			field.RelationField
			SubmissionSettings struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			AccountGroupAssignments struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
				}
			}
			AccountGroups struct {
				field.RelationField
			}
			Accounts struct {
				field.RelationField
			}
			BudgetRevisions struct {
				field.RelationField
			}
			BudgetRevisionAccountValues struct {
				field.RelationField
			}
			BudgetAccountValues struct {
				field.RelationField
			}
			Budgets struct {
				field.RelationField
			}
			LedgerYears struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			LedgerAccounts struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				CreditTransactions struct {
					field.RelationField
				}
				DebitTransactions struct {
					field.RelationField
				}
			}
			ReportTemplates struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Reports struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Transactions struct {
				field.RelationField
			}
			TransactionAssignments struct {
				field.RelationField
			}
			Committees struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				PaymentAccounts struct {
					field.RelationField
					Committee struct {
						field.RelationField
					}
				}
				Submissions struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Committee struct {
						field.RelationField
					}
					CreatedBy struct {
						field.RelationField
						UserIdentities struct {
							field.RelationField
							User struct {
								field.RelationField
							}
						}
					}
				}
			}
			Submissions struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("CreditTransactions.Organization", "model.Organization"),
			SubmissionSettings: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.SubmissionSettings", "model.OrganizationSubmissionSettings"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.SubmissionSettings.Organization", "model.Organization"),
				},
			},
			AccountGroupAssignments: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments", "model.AccountGroupAssignment"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Organization", "model.Organization"),
				},
				AccountGroup: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.AccountGroup", "model.AccountGroup"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.AccountGroup.Organization", "model.Organization"),
					},
					AccountGroupAssignments: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.AccountGroup.AccountGroupAssignments", "model.AccountGroupAssignment"),
					},
				},
				Account: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account", "model.Account"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.Organization", "model.Organization"),
					},
					ParentAccount: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.ParentAccount", "model.Account"),
					},
					ChildAccounts: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.ChildAccounts", "model.Account"),
					},
					AccountGroupAssignments: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.AccountGroupAssignments", "model.AccountGroupAssignment"),
					},
					BudgetRevisionAccountValues: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Organization", "model.Organization"),
						},
						Budget: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget", "model.Budget"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.Organization", "model.Organization"),
							},
							BudgetRevisions: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions", "model.BudgetRevision"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Organization", "model.Organization"),
								},
								Budget: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Budget", "model.Budget"),
								},
								BudgetRevisionAccountValues: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
								},
							},
							BudgetAccountValues: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues", "model.BudgetAccountValue"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Organization", "model.Organization"),
								},
								Budget: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Budget", "model.Budget"),
								},
								Account: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Account", "model.Account"),
								},
							},
						},
						BudgetRevision: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision", "model.BudgetRevision"),
						},
						Account: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Account", "model.Account"),
						},
					},
					BudgetAccountValues: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetAccountValues", "model.BudgetAccountValue"),
					},
					TransactionAssignments: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.TransactionAssignments", "model.TransactionAssignment"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.TransactionAssignments.Organization", "model.Organization"),
						},
						Transaction: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction", "model.Transaction_"),
						},
						Account: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.TransactionAssignments.Account", "model.Account"),
						},
					},
				},
			},
			AccountGroups: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroups", "model.AccountGroup"),
			},
			Accounts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.Accounts", "model.Account"),
			},
			BudgetRevisions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.BudgetRevisions", "model.BudgetRevision"),
			},
			BudgetRevisionAccountValues: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
			},
			BudgetAccountValues: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.BudgetAccountValues", "model.BudgetAccountValue"),
			},
			Budgets: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.Budgets", "model.Budget"),
			},
			LedgerYears: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.LedgerYears", "model.LedgerYear"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.LedgerYears.Organization", "model.Organization"),
				},
			},
			LedgerAccounts: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				CreditTransactions struct {
					field.RelationField
				}
				DebitTransactions struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.LedgerAccounts", "model.LedgerAccount"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.LedgerAccounts.Organization", "model.Organization"),
				},
				CreditTransactions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.LedgerAccounts.CreditTransactions", "model.Transaction_"),
				},
				DebitTransactions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.LedgerAccounts.DebitTransactions", "model.Transaction_"),
				},
			},
			ReportTemplates: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.ReportTemplates", "model.ReportTemplate"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.ReportTemplates.Organization", "model.Organization"),
				},
			},
			Reports: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.Reports", "model.Report"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.Reports.Organization", "model.Organization"),
				},
			},
			Transactions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.Transactions", "model.Transaction_"),
			},
			TransactionAssignments: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.TransactionAssignments", "model.TransactionAssignment"),
			},
			Committees: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				PaymentAccounts struct {
					field.RelationField
					Committee struct {
						field.RelationField
					}
				}
				Submissions struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Committee struct {
						field.RelationField
					}
					CreatedBy struct {
						field.RelationField
						UserIdentities struct {
							field.RelationField
							User struct {
								field.RelationField
							}
						}
					}
				}
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.Committees", "model.Committee"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.Committees.Organization", "model.Organization"),
				},
				PaymentAccounts: struct {
					field.RelationField
					Committee struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.Committees.PaymentAccounts", "model.CommitteePaymentAccount"),
					Committee: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.Committees.PaymentAccounts.Committee", "model.Committee"),
					},
				},
				Submissions: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Committee struct {
						field.RelationField
					}
					CreatedBy struct {
						field.RelationField
						UserIdentities struct {
							field.RelationField
							User struct {
								field.RelationField
							}
						}
					}
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.Committees.Submissions", "model.Submission"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.Committees.Submissions.Organization", "model.Organization"),
					},
					Committee: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.Committees.Submissions.Committee", "model.Committee"),
					},
					CreatedBy: struct {
						field.RelationField
						UserIdentities struct {
							field.RelationField
							User struct {
								field.RelationField
							}
						}
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.Committees.Submissions.CreatedBy", "model.User"),
						UserIdentities: struct {
							field.RelationField
							User struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.Committees.Submissions.CreatedBy.UserIdentities", "model.UserIdentity"),
							User: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("CreditTransactions.Organization.Committees.Submissions.CreatedBy.UserIdentities.User", "model.User"),
							},
						},
					},
				},
			},
			Submissions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.Submissions", "model.Submission"),
			},
		},
		CreditLedgerAccount: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("CreditTransactions.CreditLedgerAccount", "model.LedgerAccount"),
		},
		DebitLedgerAccount: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("CreditTransactions.DebitLedgerAccount", "model.LedgerAccount"),
		},
		TransactionAssignments: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("CreditTransactions.TransactionAssignments", "model.TransactionAssignment"),
		},
	}

	_ledgerAccount.DebitTransactions = ledgerAccountHasManyDebitTransactions{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("DebitTransactions", "model.Transaction_"),
	}

	_ledgerAccount.Organization = ledgerAccountBelongsToOrganization{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Organization", "model.Organization"),
	}

	_ledgerAccount.fillFieldMap()

	return _ledgerAccount
}

type ledgerAccount struct {
	ledgerAccountDo ledgerAccountDo

	ALL                field.Asterisk
	ID                 field.Field
	CustomID           field.String
	OrganizationID     field.Field
	Code               field.String
	AccountType        field.Int
	DisplayName        field.String
	DisplayDescription field.String
	UpdatedAt          field.Time
	CreatedAt          field.Time
	CreditTransactions ledgerAccountHasManyCreditTransactions

	DebitTransactions ledgerAccountHasManyDebitTransactions

	Organization ledgerAccountBelongsToOrganization

	fieldMap map[string]field.Expr
}

func (l ledgerAccount) Table(newTableName string) *ledgerAccount {
	l.ledgerAccountDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l ledgerAccount) As(alias string) *ledgerAccount {
	l.ledgerAccountDo.DO = *(l.ledgerAccountDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *ledgerAccount) updateTableName(table string) *ledgerAccount {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewField(table, "id")
	l.CustomID = field.NewString(table, "custom_id")
	l.OrganizationID = field.NewField(table, "organization_id")
	l.Code = field.NewString(table, "code")
	l.AccountType = field.NewInt(table, "account_type")
	l.DisplayName = field.NewString(table, "display_name")
	l.DisplayDescription = field.NewString(table, "display_description")
	l.UpdatedAt = field.NewTime(table, "updated_at")
	l.CreatedAt = field.NewTime(table, "created_at")

	l.fillFieldMap()

	return l
}

func (l *ledgerAccount) WithContext(ctx context.Context) ILedgerAccountDo {
	return l.ledgerAccountDo.WithContext(ctx)
}

func (l ledgerAccount) TableName() string { return l.ledgerAccountDo.TableName() }

func (l ledgerAccount) Alias() string { return l.ledgerAccountDo.Alias() }

func (l ledgerAccount) Columns(cols ...field.Expr) gen.Columns {
	return l.ledgerAccountDo.Columns(cols...)
}

func (l *ledgerAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *ledgerAccount) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 12)
	l.fieldMap["id"] = l.ID
	l.fieldMap["custom_id"] = l.CustomID
	l.fieldMap["organization_id"] = l.OrganizationID
	l.fieldMap["code"] = l.Code
	l.fieldMap["account_type"] = l.AccountType
	l.fieldMap["display_name"] = l.DisplayName
	l.fieldMap["display_description"] = l.DisplayDescription
	l.fieldMap["updated_at"] = l.UpdatedAt
	l.fieldMap["created_at"] = l.CreatedAt

}

func (l ledgerAccount) clone(db *gorm.DB) ledgerAccount {
	l.ledgerAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	l.CreditTransactions.db = db.Session(&gorm.Session{Initialized: true})
	l.CreditTransactions.db.Statement.ConnPool = db.Statement.ConnPool
	l.DebitTransactions.db = db.Session(&gorm.Session{Initialized: true})
	l.DebitTransactions.db.Statement.ConnPool = db.Statement.ConnPool
	l.Organization.db = db.Session(&gorm.Session{Initialized: true})
	l.Organization.db.Statement.ConnPool = db.Statement.ConnPool
	return l
}

func (l ledgerAccount) replaceDB(db *gorm.DB) ledgerAccount {
	l.ledgerAccountDo.ReplaceDB(db)
	l.CreditTransactions.db = db.Session(&gorm.Session{})
	l.DebitTransactions.db = db.Session(&gorm.Session{})
	l.Organization.db = db.Session(&gorm.Session{})
	return l
}

type ledgerAccountHasManyCreditTransactions struct {
	db *gorm.DB

	field.RelationField

	Organization struct {
		field.RelationField
		SubmissionSettings struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		AccountGroupAssignments struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroup struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}
			Account struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
				BudgetAccountValues struct {
					field.RelationField
				}
				TransactionAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
			}
		}
		AccountGroups struct {
			field.RelationField
		}
		Accounts struct {
			field.RelationField
		}
		BudgetRevisions struct {
			field.RelationField
		}
		BudgetRevisionAccountValues struct {
			field.RelationField
		}
		BudgetAccountValues struct {
			field.RelationField
		}
		Budgets struct {
			field.RelationField
		}
		LedgerYears struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		LedgerAccounts struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			CreditTransactions struct {
				field.RelationField
			}
			DebitTransactions struct {
				field.RelationField
			}
		}
		ReportTemplates struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Reports struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Transactions struct {
			field.RelationField
		}
		TransactionAssignments struct {
			field.RelationField
		}
		Committees struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			PaymentAccounts struct {
				field.RelationField
				Committee struct {
					field.RelationField
				}
			}
			Submissions struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Committee struct {
					field.RelationField
				}
				CreatedBy struct {
					field.RelationField
					UserIdentities struct {
						field.RelationField
						User struct {
							field.RelationField
						}
					}
				}
			}
		}
		Submissions struct {
			field.RelationField
		}
	}
	CreditLedgerAccount struct {
		field.RelationField
	}
	DebitLedgerAccount struct {
		field.RelationField
	}
	TransactionAssignments struct {
		field.RelationField
	}
}

func (a ledgerAccountHasManyCreditTransactions) Where(conds ...field.Expr) *ledgerAccountHasManyCreditTransactions {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a ledgerAccountHasManyCreditTransactions) WithContext(ctx context.Context) *ledgerAccountHasManyCreditTransactions {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a ledgerAccountHasManyCreditTransactions) Session(session *gorm.Session) *ledgerAccountHasManyCreditTransactions {
	a.db = a.db.Session(session)
	return &a
}

func (a ledgerAccountHasManyCreditTransactions) Model(m *model.LedgerAccount) *ledgerAccountHasManyCreditTransactionsTx {
	return &ledgerAccountHasManyCreditTransactionsTx{a.db.Model(m).Association(a.Name())}
}

func (a ledgerAccountHasManyCreditTransactions) Unscoped() *ledgerAccountHasManyCreditTransactions {
	a.db = a.db.Unscoped()
	return &a
}

type ledgerAccountHasManyCreditTransactionsTx struct{ tx *gorm.Association }

func (a ledgerAccountHasManyCreditTransactionsTx) Find() (result []*model.Transaction_, err error) {
	return result, a.tx.Find(&result)
}

func (a ledgerAccountHasManyCreditTransactionsTx) Append(values ...*model.Transaction_) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a ledgerAccountHasManyCreditTransactionsTx) Replace(values ...*model.Transaction_) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a ledgerAccountHasManyCreditTransactionsTx) Delete(values ...*model.Transaction_) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a ledgerAccountHasManyCreditTransactionsTx) Clear() error {
	return a.tx.Clear()
}

func (a ledgerAccountHasManyCreditTransactionsTx) Count() int64 {
	return a.tx.Count()
}

func (a ledgerAccountHasManyCreditTransactionsTx) Unscoped() *ledgerAccountHasManyCreditTransactionsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type ledgerAccountHasManyDebitTransactions struct {
	db *gorm.DB

	field.RelationField
}

func (a ledgerAccountHasManyDebitTransactions) Where(conds ...field.Expr) *ledgerAccountHasManyDebitTransactions {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a ledgerAccountHasManyDebitTransactions) WithContext(ctx context.Context) *ledgerAccountHasManyDebitTransactions {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a ledgerAccountHasManyDebitTransactions) Session(session *gorm.Session) *ledgerAccountHasManyDebitTransactions {
	a.db = a.db.Session(session)
	return &a
}

func (a ledgerAccountHasManyDebitTransactions) Model(m *model.LedgerAccount) *ledgerAccountHasManyDebitTransactionsTx {
	return &ledgerAccountHasManyDebitTransactionsTx{a.db.Model(m).Association(a.Name())}
}

func (a ledgerAccountHasManyDebitTransactions) Unscoped() *ledgerAccountHasManyDebitTransactions {
	a.db = a.db.Unscoped()
	return &a
}

type ledgerAccountHasManyDebitTransactionsTx struct{ tx *gorm.Association }

func (a ledgerAccountHasManyDebitTransactionsTx) Find() (result []*model.Transaction_, err error) {
	return result, a.tx.Find(&result)
}

func (a ledgerAccountHasManyDebitTransactionsTx) Append(values ...*model.Transaction_) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a ledgerAccountHasManyDebitTransactionsTx) Replace(values ...*model.Transaction_) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a ledgerAccountHasManyDebitTransactionsTx) Delete(values ...*model.Transaction_) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a ledgerAccountHasManyDebitTransactionsTx) Clear() error {
	return a.tx.Clear()
}

func (a ledgerAccountHasManyDebitTransactionsTx) Count() int64 {
	return a.tx.Count()
}

func (a ledgerAccountHasManyDebitTransactionsTx) Unscoped() *ledgerAccountHasManyDebitTransactionsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type ledgerAccountBelongsToOrganization struct {
	db *gorm.DB

	field.RelationField
}

func (a ledgerAccountBelongsToOrganization) Where(conds ...field.Expr) *ledgerAccountBelongsToOrganization {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a ledgerAccountBelongsToOrganization) WithContext(ctx context.Context) *ledgerAccountBelongsToOrganization {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a ledgerAccountBelongsToOrganization) Session(session *gorm.Session) *ledgerAccountBelongsToOrganization {
	a.db = a.db.Session(session)
	return &a
}

func (a ledgerAccountBelongsToOrganization) Model(m *model.LedgerAccount) *ledgerAccountBelongsToOrganizationTx {
	return &ledgerAccountBelongsToOrganizationTx{a.db.Model(m).Association(a.Name())}
}

func (a ledgerAccountBelongsToOrganization) Unscoped() *ledgerAccountBelongsToOrganization {
	a.db = a.db.Unscoped()
	return &a
}

type ledgerAccountBelongsToOrganizationTx struct{ tx *gorm.Association }

func (a ledgerAccountBelongsToOrganizationTx) Find() (result *model.Organization, err error) {
	return result, a.tx.Find(&result)
}

func (a ledgerAccountBelongsToOrganizationTx) Append(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a ledgerAccountBelongsToOrganizationTx) Replace(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a ledgerAccountBelongsToOrganizationTx) Delete(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a ledgerAccountBelongsToOrganizationTx) Clear() error {
	return a.tx.Clear()
}

func (a ledgerAccountBelongsToOrganizationTx) Count() int64 {
	return a.tx.Count()
}

func (a ledgerAccountBelongsToOrganizationTx) Unscoped() *ledgerAccountBelongsToOrganizationTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type ledgerAccountDo struct{ gen.DO }

type ILedgerAccountDo interface {
	gen.SubQuery
	Debug() ILedgerAccountDo
	WithContext(ctx context.Context) ILedgerAccountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILedgerAccountDo
	WriteDB() ILedgerAccountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILedgerAccountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILedgerAccountDo
	Not(conds ...gen.Condition) ILedgerAccountDo
	Or(conds ...gen.Condition) ILedgerAccountDo
	Select(conds ...field.Expr) ILedgerAccountDo
	Where(conds ...gen.Condition) ILedgerAccountDo
	Order(conds ...field.Expr) ILedgerAccountDo
	Distinct(cols ...field.Expr) ILedgerAccountDo
	Omit(cols ...field.Expr) ILedgerAccountDo
	Join(table schema.Tabler, on ...field.Expr) ILedgerAccountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILedgerAccountDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILedgerAccountDo
	Group(cols ...field.Expr) ILedgerAccountDo
	Having(conds ...gen.Condition) ILedgerAccountDo
	Limit(limit int) ILedgerAccountDo
	Offset(offset int) ILedgerAccountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILedgerAccountDo
	Unscoped() ILedgerAccountDo
	Create(values ...*model.LedgerAccount) error
	CreateInBatches(values []*model.LedgerAccount, batchSize int) error
	Save(values ...*model.LedgerAccount) error
	First() (*model.LedgerAccount, error)
	Take() (*model.LedgerAccount, error)
	Last() (*model.LedgerAccount, error)
	Find() ([]*model.LedgerAccount, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LedgerAccount, err error)
	FindInBatches(result *[]*model.LedgerAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LedgerAccount) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILedgerAccountDo
	Assign(attrs ...field.AssignExpr) ILedgerAccountDo
	Joins(fields ...field.RelationField) ILedgerAccountDo
	Preload(fields ...field.RelationField) ILedgerAccountDo
	FirstOrInit() (*model.LedgerAccount, error)
	FirstOrCreate() (*model.LedgerAccount, error)
	FindByPage(offset int, limit int) (result []*model.LedgerAccount, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILedgerAccountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l ledgerAccountDo) Debug() ILedgerAccountDo {
	return l.withDO(l.DO.Debug())
}

func (l ledgerAccountDo) WithContext(ctx context.Context) ILedgerAccountDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l ledgerAccountDo) ReadDB() ILedgerAccountDo {
	return l.Clauses(dbresolver.Read)
}

func (l ledgerAccountDo) WriteDB() ILedgerAccountDo {
	return l.Clauses(dbresolver.Write)
}

func (l ledgerAccountDo) Session(config *gorm.Session) ILedgerAccountDo {
	return l.withDO(l.DO.Session(config))
}

func (l ledgerAccountDo) Clauses(conds ...clause.Expression) ILedgerAccountDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l ledgerAccountDo) Returning(value interface{}, columns ...string) ILedgerAccountDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l ledgerAccountDo) Not(conds ...gen.Condition) ILedgerAccountDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l ledgerAccountDo) Or(conds ...gen.Condition) ILedgerAccountDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l ledgerAccountDo) Select(conds ...field.Expr) ILedgerAccountDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l ledgerAccountDo) Where(conds ...gen.Condition) ILedgerAccountDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l ledgerAccountDo) Order(conds ...field.Expr) ILedgerAccountDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l ledgerAccountDo) Distinct(cols ...field.Expr) ILedgerAccountDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l ledgerAccountDo) Omit(cols ...field.Expr) ILedgerAccountDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l ledgerAccountDo) Join(table schema.Tabler, on ...field.Expr) ILedgerAccountDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l ledgerAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILedgerAccountDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l ledgerAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) ILedgerAccountDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l ledgerAccountDo) Group(cols ...field.Expr) ILedgerAccountDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l ledgerAccountDo) Having(conds ...gen.Condition) ILedgerAccountDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l ledgerAccountDo) Limit(limit int) ILedgerAccountDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l ledgerAccountDo) Offset(offset int) ILedgerAccountDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l ledgerAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILedgerAccountDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l ledgerAccountDo) Unscoped() ILedgerAccountDo {
	return l.withDO(l.DO.Unscoped())
}

func (l ledgerAccountDo) Create(values ...*model.LedgerAccount) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l ledgerAccountDo) CreateInBatches(values []*model.LedgerAccount, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l ledgerAccountDo) Save(values ...*model.LedgerAccount) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l ledgerAccountDo) First() (*model.LedgerAccount, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LedgerAccount), nil
	}
}

func (l ledgerAccountDo) Take() (*model.LedgerAccount, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LedgerAccount), nil
	}
}

func (l ledgerAccountDo) Last() (*model.LedgerAccount, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LedgerAccount), nil
	}
}

func (l ledgerAccountDo) Find() ([]*model.LedgerAccount, error) {
	result, err := l.DO.Find()
	return result.([]*model.LedgerAccount), err
}

func (l ledgerAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LedgerAccount, err error) {
	buf := make([]*model.LedgerAccount, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l ledgerAccountDo) FindInBatches(result *[]*model.LedgerAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l ledgerAccountDo) Attrs(attrs ...field.AssignExpr) ILedgerAccountDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l ledgerAccountDo) Assign(attrs ...field.AssignExpr) ILedgerAccountDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l ledgerAccountDo) Joins(fields ...field.RelationField) ILedgerAccountDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l ledgerAccountDo) Preload(fields ...field.RelationField) ILedgerAccountDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l ledgerAccountDo) FirstOrInit() (*model.LedgerAccount, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LedgerAccount), nil
	}
}

func (l ledgerAccountDo) FirstOrCreate() (*model.LedgerAccount, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LedgerAccount), nil
	}
}

func (l ledgerAccountDo) FindByPage(offset int, limit int) (result []*model.LedgerAccount, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l ledgerAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l ledgerAccountDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l ledgerAccountDo) Delete(models ...*model.LedgerAccount) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *ledgerAccountDo) withDO(do gen.Dao) *ledgerAccountDo {
	l.DO = *do.(*gen.DO)
	return l
}
