// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"github.com/pixlcrashr/vsfv/pkg/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newOrganizationSubmissionSettings(db *gorm.DB, opts ...gen.DOOption) organizationSubmissionSettings {
	_organizationSubmissionSettings := organizationSubmissionSettings{}

	_organizationSubmissionSettings.organizationSubmissionSettingsDo.UseDB(db, opts...)
	_organizationSubmissionSettings.organizationSubmissionSettingsDo.UseModel(&model.OrganizationSubmissionSettings{})

	tableName := _organizationSubmissionSettings.organizationSubmissionSettingsDo.TableName()
	_organizationSubmissionSettings.ALL = field.NewAsterisk(tableName)
	_organizationSubmissionSettings.ID = field.NewField(tableName, "id")
	_organizationSubmissionSettings.OrganizationID = field.NewField(tableName, "organization_id")
	_organizationSubmissionSettings.EnabledSettlementKinds = field.NewField(tableName, "enabled_settlement_kinds")
	_organizationSubmissionSettings.SubmissionDeadline = field.NewTime(tableName, "submission_deadline")
	_organizationSubmissionSettings.UpdatedAt = field.NewTime(tableName, "updated_at")
	_organizationSubmissionSettings.Organization = organizationSubmissionSettingsBelongsToOrganization{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Organization", "model.Organization"),
		SubmissionSettings: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Organization.SubmissionSettings", "model.OrganizationSubmissionSettings"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.SubmissionSettings.Organization", "model.Organization"),
			},
		},
		AccountGroupAssignments: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroup struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}
			Account struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
				BudgetAccountValues struct {
					field.RelationField
				}
				TransactionAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditLedgerAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitLedgerAccount struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
			}
		}{
			RelationField: field.NewRelation("Organization.AccountGroupAssignments", "model.AccountGroupAssignment"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.AccountGroupAssignments.Organization", "model.Organization"),
			},
			AccountGroup: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Organization.AccountGroupAssignments.AccountGroup", "model.AccountGroup"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.AccountGroup.Organization", "model.Organization"),
				},
				AccountGroupAssignments: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.AccountGroup.AccountGroupAssignments", "model.AccountGroupAssignment"),
				},
			},
			Account: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
				BudgetAccountValues struct {
					field.RelationField
				}
				TransactionAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditLedgerAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitLedgerAccount struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account", "model.Account"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.Organization", "model.Organization"),
				},
				ParentAccount: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.ParentAccount", "model.Account"),
				},
				ChildAccounts: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.ChildAccounts", "model.Account"),
				},
				AccountGroupAssignments: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.AccountGroupAssignments", "model.AccountGroupAssignment"),
				},
				BudgetRevisionAccountValues: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Organization", "model.Organization"),
					},
					Budget: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget", "model.Budget"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.Organization", "model.Organization"),
						},
						BudgetRevisions: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions", "model.BudgetRevision"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Organization", "model.Organization"),
							},
							Budget: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Budget", "model.Budget"),
							},
							BudgetRevisionAccountValues: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
							},
						},
						BudgetAccountValues: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues", "model.BudgetAccountValue"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Organization", "model.Organization"),
							},
							Budget: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Budget", "model.Budget"),
							},
							Account: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Account", "model.Account"),
							},
						},
					},
					BudgetRevision: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision", "model.BudgetRevision"),
					},
					Account: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Account", "model.Account"),
					},
				},
				BudgetAccountValues: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetAccountValues", "model.BudgetAccountValue"),
				},
				TransactionAssignments: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditLedgerAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitLedgerAccount struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments", "model.TransactionAssignment"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Organization", "model.Organization"),
					},
					Transaction: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditLedgerAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitLedgerAccount struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction", "model.Transaction_"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.Organization", "model.Organization"),
						},
						CreditLedgerAccount: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount", "model.LedgerAccount"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.Organization", "model.Organization"),
							},
							CreditTransactions: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.CreditTransactions", "model.Transaction_"),
							},
							DebitTransactions: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.DebitTransactions", "model.Transaction_"),
							},
						},
						DebitLedgerAccount: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.DebitLedgerAccount", "model.LedgerAccount"),
						},
						TransactionAssignments: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.TransactionAssignments", "model.TransactionAssignment"),
						},
					},
					Account: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Account", "model.Account"),
					},
				},
			},
		},
		AccountGroups: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.AccountGroups", "model.AccountGroup"),
		},
		Accounts: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.Accounts", "model.Account"),
		},
		BudgetRevisions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.BudgetRevisions", "model.BudgetRevision"),
		},
		BudgetRevisionAccountValues: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
		},
		BudgetAccountValues: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.BudgetAccountValues", "model.BudgetAccountValue"),
		},
		Budgets: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.Budgets", "model.Budget"),
		},
		LedgerYears: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Organization.LedgerYears", "model.LedgerYear"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.LedgerYears.Organization", "model.Organization"),
			},
		},
		LedgerAccounts: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.LedgerAccounts", "model.LedgerAccount"),
		},
		ReportTemplates: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Organization.ReportTemplates", "model.ReportTemplate"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.ReportTemplates.Organization", "model.Organization"),
			},
		},
		Reports: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Organization.Reports", "model.Report"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.Reports.Organization", "model.Organization"),
			},
		},
		Transactions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.Transactions", "model.Transaction_"),
		},
		TransactionAssignments: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.TransactionAssignments", "model.TransactionAssignment"),
		},
		Committees: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			PaymentAccounts struct {
				field.RelationField
				Committee struct {
					field.RelationField
				}
			}
			Submissions struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Committee struct {
					field.RelationField
				}
				CreatedBy struct {
					field.RelationField
					UserIdentities struct {
						field.RelationField
						User struct {
							field.RelationField
						}
					}
				}
			}
		}{
			RelationField: field.NewRelation("Organization.Committees", "model.Committee"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.Committees.Organization", "model.Organization"),
			},
			PaymentAccounts: struct {
				field.RelationField
				Committee struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Organization.Committees.PaymentAccounts", "model.CommitteePaymentAccount"),
				Committee: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.Committees.PaymentAccounts.Committee", "model.Committee"),
				},
			},
			Submissions: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Committee struct {
					field.RelationField
				}
				CreatedBy struct {
					field.RelationField
					UserIdentities struct {
						field.RelationField
						User struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("Organization.Committees.Submissions", "model.Submission"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.Committees.Submissions.Organization", "model.Organization"),
				},
				Committee: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.Committees.Submissions.Committee", "model.Committee"),
				},
				CreatedBy: struct {
					field.RelationField
					UserIdentities struct {
						field.RelationField
						User struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("Organization.Committees.Submissions.CreatedBy", "model.User"),
					UserIdentities: struct {
						field.RelationField
						User struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Organization.Committees.Submissions.CreatedBy.UserIdentities", "model.UserIdentity"),
						User: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.Committees.Submissions.CreatedBy.UserIdentities.User", "model.User"),
						},
					},
				},
			},
		},
		Submissions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.Submissions", "model.Submission"),
		},
	}

	_organizationSubmissionSettings.fillFieldMap()

	return _organizationSubmissionSettings
}

type organizationSubmissionSettings struct {
	organizationSubmissionSettingsDo organizationSubmissionSettingsDo

	ALL                    field.Asterisk
	ID                     field.Field
	OrganizationID         field.Field
	EnabledSettlementKinds field.Field
	SubmissionDeadline     field.Time
	UpdatedAt              field.Time
	Organization           organizationSubmissionSettingsBelongsToOrganization

	fieldMap map[string]field.Expr
}

func (o organizationSubmissionSettings) Table(newTableName string) *organizationSubmissionSettings {
	o.organizationSubmissionSettingsDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o organizationSubmissionSettings) As(alias string) *organizationSubmissionSettings {
	o.organizationSubmissionSettingsDo.DO = *(o.organizationSubmissionSettingsDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *organizationSubmissionSettings) updateTableName(table string) *organizationSubmissionSettings {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewField(table, "id")
	o.OrganizationID = field.NewField(table, "organization_id")
	o.EnabledSettlementKinds = field.NewField(table, "enabled_settlement_kinds")
	o.SubmissionDeadline = field.NewTime(table, "submission_deadline")
	o.UpdatedAt = field.NewTime(table, "updated_at")

	o.fillFieldMap()

	return o
}

func (o *organizationSubmissionSettings) WithContext(ctx context.Context) IOrganizationSubmissionSettingsDo {
	return o.organizationSubmissionSettingsDo.WithContext(ctx)
}

func (o organizationSubmissionSettings) TableName() string {
	return o.organizationSubmissionSettingsDo.TableName()
}

func (o organizationSubmissionSettings) Alias() string {
	return o.organizationSubmissionSettingsDo.Alias()
}

func (o organizationSubmissionSettings) Columns(cols ...field.Expr) gen.Columns {
	return o.organizationSubmissionSettingsDo.Columns(cols...)
}

func (o *organizationSubmissionSettings) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *organizationSubmissionSettings) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 6)
	o.fieldMap["id"] = o.ID
	o.fieldMap["organization_id"] = o.OrganizationID
	o.fieldMap["enabled_settlement_kinds"] = o.EnabledSettlementKinds
	o.fieldMap["submission_deadline"] = o.SubmissionDeadline
	o.fieldMap["updated_at"] = o.UpdatedAt

}

func (o organizationSubmissionSettings) clone(db *gorm.DB) organizationSubmissionSettings {
	o.organizationSubmissionSettingsDo.ReplaceConnPool(db.Statement.ConnPool)
	o.Organization.db = db.Session(&gorm.Session{Initialized: true})
	o.Organization.db.Statement.ConnPool = db.Statement.ConnPool
	return o
}

func (o organizationSubmissionSettings) replaceDB(db *gorm.DB) organizationSubmissionSettings {
	o.organizationSubmissionSettingsDo.ReplaceDB(db)
	o.Organization.db = db.Session(&gorm.Session{})
	return o
}

type organizationSubmissionSettingsBelongsToOrganization struct {
	db *gorm.DB

	field.RelationField

	SubmissionSettings struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
	}
	AccountGroupAssignments struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
		AccountGroup struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroupAssignments struct {
				field.RelationField
			}
		}
		Account struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			ParentAccount struct {
				field.RelationField
			}
			ChildAccounts struct {
				field.RelationField
			}
			AccountGroupAssignments struct {
				field.RelationField
			}
			BudgetRevisionAccountValues struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Budget struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					BudgetRevisions struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
						}
						BudgetRevisionAccountValues struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
				}
				BudgetRevision struct {
					field.RelationField
				}
				Account struct {
					field.RelationField
				}
			}
			BudgetAccountValues struct {
				field.RelationField
			}
			TransactionAssignments struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Transaction struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					CreditLedgerAccount struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditTransactions struct {
							field.RelationField
						}
						DebitTransactions struct {
							field.RelationField
						}
					}
					DebitLedgerAccount struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
				}
			}
		}
	}
	AccountGroups struct {
		field.RelationField
	}
	Accounts struct {
		field.RelationField
	}
	BudgetRevisions struct {
		field.RelationField
	}
	BudgetRevisionAccountValues struct {
		field.RelationField
	}
	BudgetAccountValues struct {
		field.RelationField
	}
	Budgets struct {
		field.RelationField
	}
	LedgerYears struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
	}
	LedgerAccounts struct {
		field.RelationField
	}
	ReportTemplates struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
	}
	Reports struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
	}
	Transactions struct {
		field.RelationField
	}
	TransactionAssignments struct {
		field.RelationField
	}
	Committees struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
		PaymentAccounts struct {
			field.RelationField
			Committee struct {
				field.RelationField
			}
		}
		Submissions struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			Committee struct {
				field.RelationField
			}
			CreatedBy struct {
				field.RelationField
				UserIdentities struct {
					field.RelationField
					User struct {
						field.RelationField
					}
				}
			}
		}
	}
	Submissions struct {
		field.RelationField
	}
}

func (a organizationSubmissionSettingsBelongsToOrganization) Where(conds ...field.Expr) *organizationSubmissionSettingsBelongsToOrganization {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a organizationSubmissionSettingsBelongsToOrganization) WithContext(ctx context.Context) *organizationSubmissionSettingsBelongsToOrganization {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a organizationSubmissionSettingsBelongsToOrganization) Session(session *gorm.Session) *organizationSubmissionSettingsBelongsToOrganization {
	a.db = a.db.Session(session)
	return &a
}

func (a organizationSubmissionSettingsBelongsToOrganization) Model(m *model.OrganizationSubmissionSettings) *organizationSubmissionSettingsBelongsToOrganizationTx {
	return &organizationSubmissionSettingsBelongsToOrganizationTx{a.db.Model(m).Association(a.Name())}
}

func (a organizationSubmissionSettingsBelongsToOrganization) Unscoped() *organizationSubmissionSettingsBelongsToOrganization {
	a.db = a.db.Unscoped()
	return &a
}

type organizationSubmissionSettingsBelongsToOrganizationTx struct{ tx *gorm.Association }

func (a organizationSubmissionSettingsBelongsToOrganizationTx) Find() (result *model.Organization, err error) {
	return result, a.tx.Find(&result)
}

func (a organizationSubmissionSettingsBelongsToOrganizationTx) Append(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a organizationSubmissionSettingsBelongsToOrganizationTx) Replace(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a organizationSubmissionSettingsBelongsToOrganizationTx) Delete(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a organizationSubmissionSettingsBelongsToOrganizationTx) Clear() error {
	return a.tx.Clear()
}

func (a organizationSubmissionSettingsBelongsToOrganizationTx) Count() int64 {
	return a.tx.Count()
}

func (a organizationSubmissionSettingsBelongsToOrganizationTx) Unscoped() *organizationSubmissionSettingsBelongsToOrganizationTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type organizationSubmissionSettingsDo struct{ gen.DO }

type IOrganizationSubmissionSettingsDo interface {
	gen.SubQuery
	Debug() IOrganizationSubmissionSettingsDo
	WithContext(ctx context.Context) IOrganizationSubmissionSettingsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOrganizationSubmissionSettingsDo
	WriteDB() IOrganizationSubmissionSettingsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOrganizationSubmissionSettingsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOrganizationSubmissionSettingsDo
	Not(conds ...gen.Condition) IOrganizationSubmissionSettingsDo
	Or(conds ...gen.Condition) IOrganizationSubmissionSettingsDo
	Select(conds ...field.Expr) IOrganizationSubmissionSettingsDo
	Where(conds ...gen.Condition) IOrganizationSubmissionSettingsDo
	Order(conds ...field.Expr) IOrganizationSubmissionSettingsDo
	Distinct(cols ...field.Expr) IOrganizationSubmissionSettingsDo
	Omit(cols ...field.Expr) IOrganizationSubmissionSettingsDo
	Join(table schema.Tabler, on ...field.Expr) IOrganizationSubmissionSettingsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOrganizationSubmissionSettingsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOrganizationSubmissionSettingsDo
	Group(cols ...field.Expr) IOrganizationSubmissionSettingsDo
	Having(conds ...gen.Condition) IOrganizationSubmissionSettingsDo
	Limit(limit int) IOrganizationSubmissionSettingsDo
	Offset(offset int) IOrganizationSubmissionSettingsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOrganizationSubmissionSettingsDo
	Unscoped() IOrganizationSubmissionSettingsDo
	Create(values ...*model.OrganizationSubmissionSettings) error
	CreateInBatches(values []*model.OrganizationSubmissionSettings, batchSize int) error
	Save(values ...*model.OrganizationSubmissionSettings) error
	First() (*model.OrganizationSubmissionSettings, error)
	Take() (*model.OrganizationSubmissionSettings, error)
	Last() (*model.OrganizationSubmissionSettings, error)
	Find() ([]*model.OrganizationSubmissionSettings, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OrganizationSubmissionSettings, err error)
	FindInBatches(result *[]*model.OrganizationSubmissionSettings, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.OrganizationSubmissionSettings) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOrganizationSubmissionSettingsDo
	Assign(attrs ...field.AssignExpr) IOrganizationSubmissionSettingsDo
	Joins(fields ...field.RelationField) IOrganizationSubmissionSettingsDo
	Preload(fields ...field.RelationField) IOrganizationSubmissionSettingsDo
	FirstOrInit() (*model.OrganizationSubmissionSettings, error)
	FirstOrCreate() (*model.OrganizationSubmissionSettings, error)
	FindByPage(offset int, limit int) (result []*model.OrganizationSubmissionSettings, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOrganizationSubmissionSettingsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o organizationSubmissionSettingsDo) Debug() IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Debug())
}

func (o organizationSubmissionSettingsDo) WithContext(ctx context.Context) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o organizationSubmissionSettingsDo) ReadDB() IOrganizationSubmissionSettingsDo {
	return o.Clauses(dbresolver.Read)
}

func (o organizationSubmissionSettingsDo) WriteDB() IOrganizationSubmissionSettingsDo {
	return o.Clauses(dbresolver.Write)
}

func (o organizationSubmissionSettingsDo) Session(config *gorm.Session) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Session(config))
}

func (o organizationSubmissionSettingsDo) Clauses(conds ...clause.Expression) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o organizationSubmissionSettingsDo) Returning(value interface{}, columns ...string) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o organizationSubmissionSettingsDo) Not(conds ...gen.Condition) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o organizationSubmissionSettingsDo) Or(conds ...gen.Condition) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o organizationSubmissionSettingsDo) Select(conds ...field.Expr) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o organizationSubmissionSettingsDo) Where(conds ...gen.Condition) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o organizationSubmissionSettingsDo) Order(conds ...field.Expr) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o organizationSubmissionSettingsDo) Distinct(cols ...field.Expr) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o organizationSubmissionSettingsDo) Omit(cols ...field.Expr) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o organizationSubmissionSettingsDo) Join(table schema.Tabler, on ...field.Expr) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o organizationSubmissionSettingsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o organizationSubmissionSettingsDo) RightJoin(table schema.Tabler, on ...field.Expr) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o organizationSubmissionSettingsDo) Group(cols ...field.Expr) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o organizationSubmissionSettingsDo) Having(conds ...gen.Condition) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o organizationSubmissionSettingsDo) Limit(limit int) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o organizationSubmissionSettingsDo) Offset(offset int) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o organizationSubmissionSettingsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o organizationSubmissionSettingsDo) Unscoped() IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Unscoped())
}

func (o organizationSubmissionSettingsDo) Create(values ...*model.OrganizationSubmissionSettings) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o organizationSubmissionSettingsDo) CreateInBatches(values []*model.OrganizationSubmissionSettings, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o organizationSubmissionSettingsDo) Save(values ...*model.OrganizationSubmissionSettings) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o organizationSubmissionSettingsDo) First() (*model.OrganizationSubmissionSettings, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrganizationSubmissionSettings), nil
	}
}

func (o organizationSubmissionSettingsDo) Take() (*model.OrganizationSubmissionSettings, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrganizationSubmissionSettings), nil
	}
}

func (o organizationSubmissionSettingsDo) Last() (*model.OrganizationSubmissionSettings, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrganizationSubmissionSettings), nil
	}
}

func (o organizationSubmissionSettingsDo) Find() ([]*model.OrganizationSubmissionSettings, error) {
	result, err := o.DO.Find()
	return result.([]*model.OrganizationSubmissionSettings), err
}

func (o organizationSubmissionSettingsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OrganizationSubmissionSettings, err error) {
	buf := make([]*model.OrganizationSubmissionSettings, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o organizationSubmissionSettingsDo) FindInBatches(result *[]*model.OrganizationSubmissionSettings, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o organizationSubmissionSettingsDo) Attrs(attrs ...field.AssignExpr) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o organizationSubmissionSettingsDo) Assign(attrs ...field.AssignExpr) IOrganizationSubmissionSettingsDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o organizationSubmissionSettingsDo) Joins(fields ...field.RelationField) IOrganizationSubmissionSettingsDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o organizationSubmissionSettingsDo) Preload(fields ...field.RelationField) IOrganizationSubmissionSettingsDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o organizationSubmissionSettingsDo) FirstOrInit() (*model.OrganizationSubmissionSettings, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrganizationSubmissionSettings), nil
	}
}

func (o organizationSubmissionSettingsDo) FirstOrCreate() (*model.OrganizationSubmissionSettings, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrganizationSubmissionSettings), nil
	}
}

func (o organizationSubmissionSettingsDo) FindByPage(offset int, limit int) (result []*model.OrganizationSubmissionSettings, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o organizationSubmissionSettingsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o organizationSubmissionSettingsDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o organizationSubmissionSettingsDo) Delete(models ...*model.OrganizationSubmissionSettings) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *organizationSubmissionSettingsDo) withDO(do gen.Dao) *organizationSubmissionSettingsDo {
	o.DO = *do.(*gen.DO)
	return o
}
