// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"github.com/pixlcrashr/vsfv/pkg/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSubmissionItem(db *gorm.DB, opts ...gen.DOOption) submissionItem {
	_submissionItem := submissionItem{}

	_submissionItem.submissionItemDo.UseDB(db, opts...)
	_submissionItem.submissionItemDo.UseModel(&model.SubmissionItem{})

	tableName := _submissionItem.submissionItemDo.TableName()
	_submissionItem.ALL = field.NewAsterisk(tableName)
	_submissionItem.ID = field.NewField(tableName, "id")
	_submissionItem.PublicID = field.NewString(tableName, "public_id")
	_submissionItem.SubmissionID = field.NewField(tableName, "submission_id")
	_submissionItem.Category = field.NewString(tableName, "category")
	_submissionItem.DocumentForm = field.NewInt(tableName, "document_form")
	_submissionItem.Source = field.NewString(tableName, "source")
	_submissionItem.Description = field.NewString(tableName, "description")
	_submissionItem.Amount = field.NewField(tableName, "amount")
	_submissionItem.OriginalReceiveTime = field.NewTime(tableName, "original_receive_time")
	_submissionItem.OriginalReceivedByUserID = field.NewField(tableName, "original_received_by_user_id")
	_submissionItem.CreatedAt = field.NewTime(tableName, "created_at")
	_submissionItem.UpdatedAt = field.NewTime(tableName, "updated_at")
	_submissionItem.Submission = submissionItemBelongsToSubmission{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Submission", "model.Submission"),
		Organization: struct {
			field.RelationField
			SubmissionSettings struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			AccountGroupAssignments struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
				}
			}
			AccountGroups struct {
				field.RelationField
			}
			Accounts struct {
				field.RelationField
			}
			BudgetRevisions struct {
				field.RelationField
			}
			BudgetRevisionAccountValues struct {
				field.RelationField
			}
			BudgetAccountValues struct {
				field.RelationField
			}
			Budgets struct {
				field.RelationField
			}
			LedgerYears struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			LedgerAccounts struct {
				field.RelationField
			}
			ReportTemplates struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Reports struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Transactions struct {
				field.RelationField
			}
			TransactionAssignments struct {
				field.RelationField
			}
			Committees struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				PaymentAccounts struct {
					field.RelationField
					Committee struct {
						field.RelationField
					}
				}
				Submissions struct {
					field.RelationField
				}
			}
			Submissions struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Submission.Organization", "model.Organization"),
			SubmissionSettings: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Submission.Organization.SubmissionSettings", "model.OrganizationSubmissionSettings"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.Organization.SubmissionSettings.Organization", "model.Organization"),
				},
			},
			AccountGroupAssignments: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments", "model.AccountGroupAssignment"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Organization", "model.Organization"),
				},
				AccountGroup: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.AccountGroup", "model.AccountGroup"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.AccountGroup.Organization", "model.Organization"),
					},
					AccountGroupAssignments: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.AccountGroup.AccountGroupAssignments", "model.AccountGroupAssignment"),
					},
				},
				Account: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account", "model.Account"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.Organization", "model.Organization"),
					},
					ParentAccount: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.ParentAccount", "model.Account"),
					},
					ChildAccounts: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.ChildAccounts", "model.Account"),
					},
					AccountGroupAssignments: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.AccountGroupAssignments", "model.AccountGroupAssignment"),
					},
					BudgetRevisionAccountValues: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Organization", "model.Organization"),
						},
						Budget: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}{
							RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget", "model.Budget"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.Organization", "model.Organization"),
							},
							BudgetRevisions: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions", "model.BudgetRevision"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Organization", "model.Organization"),
								},
								Budget: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Budget", "model.Budget"),
								},
								BudgetRevisionAccountValues: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
								},
							},
							BudgetAccountValues: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues", "model.BudgetAccountValue"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Organization", "model.Organization"),
								},
								Budget: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Budget", "model.Budget"),
								},
								Account: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Account", "model.Account"),
								},
							},
						},
						BudgetRevision: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision", "model.BudgetRevision"),
						},
						Account: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Account", "model.Account"),
						},
					},
					BudgetAccountValues: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetAccountValues", "model.BudgetAccountValue"),
					},
					TransactionAssignments: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments", "model.TransactionAssignment"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Organization", "model.Organization"),
						},
						Transaction: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction", "model.Transaction_"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.Organization", "model.Organization"),
							},
							CreditLedgerAccount: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount", "model.LedgerAccount"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.Organization", "model.Organization"),
								},
								CreditTransactions: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.CreditTransactions", "model.Transaction_"),
								},
								DebitTransactions: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.DebitTransactions", "model.Transaction_"),
								},
							},
							DebitLedgerAccount: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.DebitLedgerAccount", "model.LedgerAccount"),
							},
							TransactionAssignments: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.TransactionAssignments", "model.TransactionAssignment"),
							},
						},
						Account: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Account", "model.Account"),
						},
					},
				},
			},
			AccountGroups: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.AccountGroups", "model.AccountGroup"),
			},
			Accounts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.Accounts", "model.Account"),
			},
			BudgetRevisions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.BudgetRevisions", "model.BudgetRevision"),
			},
			BudgetRevisionAccountValues: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
			},
			BudgetAccountValues: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.BudgetAccountValues", "model.BudgetAccountValue"),
			},
			Budgets: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.Budgets", "model.Budget"),
			},
			LedgerYears: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Submission.Organization.LedgerYears", "model.LedgerYear"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.Organization.LedgerYears.Organization", "model.Organization"),
				},
			},
			LedgerAccounts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.LedgerAccounts", "model.LedgerAccount"),
			},
			ReportTemplates: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Submission.Organization.ReportTemplates", "model.ReportTemplate"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.Organization.ReportTemplates.Organization", "model.Organization"),
				},
			},
			Reports: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Submission.Organization.Reports", "model.Report"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.Organization.Reports.Organization", "model.Organization"),
				},
			},
			Transactions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.Transactions", "model.Transaction_"),
			},
			TransactionAssignments: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.TransactionAssignments", "model.TransactionAssignment"),
			},
			Committees: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				PaymentAccounts struct {
					field.RelationField
					Committee struct {
						field.RelationField
					}
				}
				Submissions struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Submission.Organization.Committees", "model.Committee"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.Organization.Committees.Organization", "model.Organization"),
				},
				PaymentAccounts: struct {
					field.RelationField
					Committee struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Submission.Organization.Committees.PaymentAccounts", "model.CommitteePaymentAccount"),
					Committee: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.Committees.PaymentAccounts.Committee", "model.Committee"),
					},
				},
				Submissions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.Organization.Committees.Submissions", "model.Submission"),
				},
			},
			Submissions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.Submissions", "model.Submission"),
			},
		},
		Committee: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Submission.Committee", "model.Committee"),
		},
		CreatedBy: struct {
			field.RelationField
			UserIdentities struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Submission.CreatedBy", "model.User"),
			UserIdentities: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Submission.CreatedBy.UserIdentities", "model.UserIdentity"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.CreatedBy.UserIdentities.User", "model.User"),
				},
			},
		},
	}

	_submissionItem.OriginalReceivedBy = submissionItemBelongsToOriginalReceivedBy{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("OriginalReceivedBy", "model.User"),
	}

	_submissionItem.fillFieldMap()

	return _submissionItem
}

type submissionItem struct {
	submissionItemDo submissionItemDo

	ALL                      field.Asterisk
	ID                       field.Field
	PublicID                 field.String
	SubmissionID             field.Field
	Category                 field.String
	DocumentForm             field.Int
	Source                   field.String
	Description              field.String
	Amount                   field.Field
	OriginalReceiveTime      field.Time
	OriginalReceivedByUserID field.Field
	CreatedAt                field.Time
	UpdatedAt                field.Time
	Submission               submissionItemBelongsToSubmission

	OriginalReceivedBy submissionItemBelongsToOriginalReceivedBy

	fieldMap map[string]field.Expr
}

func (s submissionItem) Table(newTableName string) *submissionItem {
	s.submissionItemDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s submissionItem) As(alias string) *submissionItem {
	s.submissionItemDo.DO = *(s.submissionItemDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *submissionItem) updateTableName(table string) *submissionItem {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewField(table, "id")
	s.PublicID = field.NewString(table, "public_id")
	s.SubmissionID = field.NewField(table, "submission_id")
	s.Category = field.NewString(table, "category")
	s.DocumentForm = field.NewInt(table, "document_form")
	s.Source = field.NewString(table, "source")
	s.Description = field.NewString(table, "description")
	s.Amount = field.NewField(table, "amount")
	s.OriginalReceiveTime = field.NewTime(table, "original_receive_time")
	s.OriginalReceivedByUserID = field.NewField(table, "original_received_by_user_id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *submissionItem) WithContext(ctx context.Context) ISubmissionItemDo {
	return s.submissionItemDo.WithContext(ctx)
}

func (s submissionItem) TableName() string { return s.submissionItemDo.TableName() }

func (s submissionItem) Alias() string { return s.submissionItemDo.Alias() }

func (s submissionItem) Columns(cols ...field.Expr) gen.Columns {
	return s.submissionItemDo.Columns(cols...)
}

func (s *submissionItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *submissionItem) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 14)
	s.fieldMap["id"] = s.ID
	s.fieldMap["public_id"] = s.PublicID
	s.fieldMap["submission_id"] = s.SubmissionID
	s.fieldMap["category"] = s.Category
	s.fieldMap["document_form"] = s.DocumentForm
	s.fieldMap["source"] = s.Source
	s.fieldMap["description"] = s.Description
	s.fieldMap["amount"] = s.Amount
	s.fieldMap["original_receive_time"] = s.OriginalReceiveTime
	s.fieldMap["original_received_by_user_id"] = s.OriginalReceivedByUserID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt

}

func (s submissionItem) clone(db *gorm.DB) submissionItem {
	s.submissionItemDo.ReplaceConnPool(db.Statement.ConnPool)
	s.Submission.db = db.Session(&gorm.Session{Initialized: true})
	s.Submission.db.Statement.ConnPool = db.Statement.ConnPool
	s.OriginalReceivedBy.db = db.Session(&gorm.Session{Initialized: true})
	s.OriginalReceivedBy.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s submissionItem) replaceDB(db *gorm.DB) submissionItem {
	s.submissionItemDo.ReplaceDB(db)
	s.Submission.db = db.Session(&gorm.Session{})
	s.OriginalReceivedBy.db = db.Session(&gorm.Session{})
	return s
}

type submissionItemBelongsToSubmission struct {
	db *gorm.DB

	field.RelationField

	Organization struct {
		field.RelationField
		SubmissionSettings struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		AccountGroupAssignments struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroup struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}
			Account struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
				BudgetAccountValues struct {
					field.RelationField
				}
				TransactionAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditLedgerAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitLedgerAccount struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
			}
		}
		AccountGroups struct {
			field.RelationField
		}
		Accounts struct {
			field.RelationField
		}
		BudgetRevisions struct {
			field.RelationField
		}
		BudgetRevisionAccountValues struct {
			field.RelationField
		}
		BudgetAccountValues struct {
			field.RelationField
		}
		Budgets struct {
			field.RelationField
		}
		LedgerYears struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		LedgerAccounts struct {
			field.RelationField
		}
		ReportTemplates struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Reports struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Transactions struct {
			field.RelationField
		}
		TransactionAssignments struct {
			field.RelationField
		}
		Committees struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			PaymentAccounts struct {
				field.RelationField
				Committee struct {
					field.RelationField
				}
			}
			Submissions struct {
				field.RelationField
			}
		}
		Submissions struct {
			field.RelationField
		}
	}
	Committee struct {
		field.RelationField
	}
	CreatedBy struct {
		field.RelationField
		UserIdentities struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}
	}
}

func (a submissionItemBelongsToSubmission) Where(conds ...field.Expr) *submissionItemBelongsToSubmission {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a submissionItemBelongsToSubmission) WithContext(ctx context.Context) *submissionItemBelongsToSubmission {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a submissionItemBelongsToSubmission) Session(session *gorm.Session) *submissionItemBelongsToSubmission {
	a.db = a.db.Session(session)
	return &a
}

func (a submissionItemBelongsToSubmission) Model(m *model.SubmissionItem) *submissionItemBelongsToSubmissionTx {
	return &submissionItemBelongsToSubmissionTx{a.db.Model(m).Association(a.Name())}
}

func (a submissionItemBelongsToSubmission) Unscoped() *submissionItemBelongsToSubmission {
	a.db = a.db.Unscoped()
	return &a
}

type submissionItemBelongsToSubmissionTx struct{ tx *gorm.Association }

func (a submissionItemBelongsToSubmissionTx) Find() (result *model.Submission, err error) {
	return result, a.tx.Find(&result)
}

func (a submissionItemBelongsToSubmissionTx) Append(values ...*model.Submission) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a submissionItemBelongsToSubmissionTx) Replace(values ...*model.Submission) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a submissionItemBelongsToSubmissionTx) Delete(values ...*model.Submission) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a submissionItemBelongsToSubmissionTx) Clear() error {
	return a.tx.Clear()
}

func (a submissionItemBelongsToSubmissionTx) Count() int64 {
	return a.tx.Count()
}

func (a submissionItemBelongsToSubmissionTx) Unscoped() *submissionItemBelongsToSubmissionTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type submissionItemBelongsToOriginalReceivedBy struct {
	db *gorm.DB

	field.RelationField
}

func (a submissionItemBelongsToOriginalReceivedBy) Where(conds ...field.Expr) *submissionItemBelongsToOriginalReceivedBy {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a submissionItemBelongsToOriginalReceivedBy) WithContext(ctx context.Context) *submissionItemBelongsToOriginalReceivedBy {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a submissionItemBelongsToOriginalReceivedBy) Session(session *gorm.Session) *submissionItemBelongsToOriginalReceivedBy {
	a.db = a.db.Session(session)
	return &a
}

func (a submissionItemBelongsToOriginalReceivedBy) Model(m *model.SubmissionItem) *submissionItemBelongsToOriginalReceivedByTx {
	return &submissionItemBelongsToOriginalReceivedByTx{a.db.Model(m).Association(a.Name())}
}

func (a submissionItemBelongsToOriginalReceivedBy) Unscoped() *submissionItemBelongsToOriginalReceivedBy {
	a.db = a.db.Unscoped()
	return &a
}

type submissionItemBelongsToOriginalReceivedByTx struct{ tx *gorm.Association }

func (a submissionItemBelongsToOriginalReceivedByTx) Find() (result *model.User, err error) {
	return result, a.tx.Find(&result)
}

func (a submissionItemBelongsToOriginalReceivedByTx) Append(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a submissionItemBelongsToOriginalReceivedByTx) Replace(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a submissionItemBelongsToOriginalReceivedByTx) Delete(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a submissionItemBelongsToOriginalReceivedByTx) Clear() error {
	return a.tx.Clear()
}

func (a submissionItemBelongsToOriginalReceivedByTx) Count() int64 {
	return a.tx.Count()
}

func (a submissionItemBelongsToOriginalReceivedByTx) Unscoped() *submissionItemBelongsToOriginalReceivedByTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type submissionItemDo struct{ gen.DO }

type ISubmissionItemDo interface {
	gen.SubQuery
	Debug() ISubmissionItemDo
	WithContext(ctx context.Context) ISubmissionItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISubmissionItemDo
	WriteDB() ISubmissionItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISubmissionItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISubmissionItemDo
	Not(conds ...gen.Condition) ISubmissionItemDo
	Or(conds ...gen.Condition) ISubmissionItemDo
	Select(conds ...field.Expr) ISubmissionItemDo
	Where(conds ...gen.Condition) ISubmissionItemDo
	Order(conds ...field.Expr) ISubmissionItemDo
	Distinct(cols ...field.Expr) ISubmissionItemDo
	Omit(cols ...field.Expr) ISubmissionItemDo
	Join(table schema.Tabler, on ...field.Expr) ISubmissionItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISubmissionItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISubmissionItemDo
	Group(cols ...field.Expr) ISubmissionItemDo
	Having(conds ...gen.Condition) ISubmissionItemDo
	Limit(limit int) ISubmissionItemDo
	Offset(offset int) ISubmissionItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISubmissionItemDo
	Unscoped() ISubmissionItemDo
	Create(values ...*model.SubmissionItem) error
	CreateInBatches(values []*model.SubmissionItem, batchSize int) error
	Save(values ...*model.SubmissionItem) error
	First() (*model.SubmissionItem, error)
	Take() (*model.SubmissionItem, error)
	Last() (*model.SubmissionItem, error)
	Find() ([]*model.SubmissionItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SubmissionItem, err error)
	FindInBatches(result *[]*model.SubmissionItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SubmissionItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISubmissionItemDo
	Assign(attrs ...field.AssignExpr) ISubmissionItemDo
	Joins(fields ...field.RelationField) ISubmissionItemDo
	Preload(fields ...field.RelationField) ISubmissionItemDo
	FirstOrInit() (*model.SubmissionItem, error)
	FirstOrCreate() (*model.SubmissionItem, error)
	FindByPage(offset int, limit int) (result []*model.SubmissionItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISubmissionItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s submissionItemDo) Debug() ISubmissionItemDo {
	return s.withDO(s.DO.Debug())
}

func (s submissionItemDo) WithContext(ctx context.Context) ISubmissionItemDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s submissionItemDo) ReadDB() ISubmissionItemDo {
	return s.Clauses(dbresolver.Read)
}

func (s submissionItemDo) WriteDB() ISubmissionItemDo {
	return s.Clauses(dbresolver.Write)
}

func (s submissionItemDo) Session(config *gorm.Session) ISubmissionItemDo {
	return s.withDO(s.DO.Session(config))
}

func (s submissionItemDo) Clauses(conds ...clause.Expression) ISubmissionItemDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s submissionItemDo) Returning(value interface{}, columns ...string) ISubmissionItemDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s submissionItemDo) Not(conds ...gen.Condition) ISubmissionItemDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s submissionItemDo) Or(conds ...gen.Condition) ISubmissionItemDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s submissionItemDo) Select(conds ...field.Expr) ISubmissionItemDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s submissionItemDo) Where(conds ...gen.Condition) ISubmissionItemDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s submissionItemDo) Order(conds ...field.Expr) ISubmissionItemDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s submissionItemDo) Distinct(cols ...field.Expr) ISubmissionItemDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s submissionItemDo) Omit(cols ...field.Expr) ISubmissionItemDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s submissionItemDo) Join(table schema.Tabler, on ...field.Expr) ISubmissionItemDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s submissionItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISubmissionItemDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s submissionItemDo) RightJoin(table schema.Tabler, on ...field.Expr) ISubmissionItemDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s submissionItemDo) Group(cols ...field.Expr) ISubmissionItemDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s submissionItemDo) Having(conds ...gen.Condition) ISubmissionItemDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s submissionItemDo) Limit(limit int) ISubmissionItemDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s submissionItemDo) Offset(offset int) ISubmissionItemDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s submissionItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISubmissionItemDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s submissionItemDo) Unscoped() ISubmissionItemDo {
	return s.withDO(s.DO.Unscoped())
}

func (s submissionItemDo) Create(values ...*model.SubmissionItem) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s submissionItemDo) CreateInBatches(values []*model.SubmissionItem, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s submissionItemDo) Save(values ...*model.SubmissionItem) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s submissionItemDo) First() (*model.SubmissionItem, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubmissionItem), nil
	}
}

func (s submissionItemDo) Take() (*model.SubmissionItem, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubmissionItem), nil
	}
}

func (s submissionItemDo) Last() (*model.SubmissionItem, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubmissionItem), nil
	}
}

func (s submissionItemDo) Find() ([]*model.SubmissionItem, error) {
	result, err := s.DO.Find()
	return result.([]*model.SubmissionItem), err
}

func (s submissionItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SubmissionItem, err error) {
	buf := make([]*model.SubmissionItem, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s submissionItemDo) FindInBatches(result *[]*model.SubmissionItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s submissionItemDo) Attrs(attrs ...field.AssignExpr) ISubmissionItemDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s submissionItemDo) Assign(attrs ...field.AssignExpr) ISubmissionItemDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s submissionItemDo) Joins(fields ...field.RelationField) ISubmissionItemDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s submissionItemDo) Preload(fields ...field.RelationField) ISubmissionItemDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s submissionItemDo) FirstOrInit() (*model.SubmissionItem, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubmissionItem), nil
	}
}

func (s submissionItemDo) FirstOrCreate() (*model.SubmissionItem, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubmissionItem), nil
	}
}

func (s submissionItemDo) FindByPage(offset int, limit int) (result []*model.SubmissionItem, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s submissionItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s submissionItemDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s submissionItemDo) Delete(models ...*model.SubmissionItem) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *submissionItemDo) withDO(do gen.Dao) *submissionItemDo {
	s.DO = *do.(*gen.DO)
	return s
}
