// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"github.com/pixlcrashr/vsfv/pkg/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSubmissionComment(db *gorm.DB, opts ...gen.DOOption) submissionComment {
	_submissionComment := submissionComment{}

	_submissionComment.submissionCommentDo.UseDB(db, opts...)
	_submissionComment.submissionCommentDo.UseModel(&model.SubmissionComment{})

	tableName := _submissionComment.submissionCommentDo.TableName()
	_submissionComment.ALL = field.NewAsterisk(tableName)
	_submissionComment.ID = field.NewField(tableName, "id")
	_submissionComment.SubmissionID = field.NewField(tableName, "submission_id")
	_submissionComment.AuthorUserID = field.NewField(tableName, "author_user_id")
	_submissionComment.Content = field.NewString(tableName, "content")
	_submissionComment.IsAdminOnly = field.NewBool(tableName, "is_admin_only")
	_submissionComment.StatusFrom = field.NewInt32(tableName, "status_from")
	_submissionComment.StatusTo = field.NewInt32(tableName, "status_to")
	_submissionComment.CreatedAt = field.NewTime(tableName, "created_at")
	_submissionComment.Submission = submissionCommentBelongsToSubmission{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Submission", "model.Submission"),
		Organization: struct {
			field.RelationField
			SubmissionSettings struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			AccountGroupAssignments struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
				}
			}
			AccountGroups struct {
				field.RelationField
			}
			Accounts struct {
				field.RelationField
			}
			BudgetRevisions struct {
				field.RelationField
			}
			BudgetRevisionAccountValues struct {
				field.RelationField
			}
			BudgetAccountValues struct {
				field.RelationField
			}
			Budgets struct {
				field.RelationField
			}
			LedgerYears struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			LedgerAccounts struct {
				field.RelationField
			}
			ReportTemplates struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Reports struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Transactions struct {
				field.RelationField
			}
			TransactionAssignments struct {
				field.RelationField
			}
			Committees struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				PaymentAccounts struct {
					field.RelationField
					Committee struct {
						field.RelationField
					}
				}
				Submissions struct {
					field.RelationField
				}
			}
			Submissions struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Submission.Organization", "model.Organization"),
			SubmissionSettings: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Submission.Organization.SubmissionSettings", "model.OrganizationSubmissionSettings"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.Organization.SubmissionSettings.Organization", "model.Organization"),
				},
			},
			AccountGroupAssignments: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments", "model.AccountGroupAssignment"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Organization", "model.Organization"),
				},
				AccountGroup: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.AccountGroup", "model.AccountGroup"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.AccountGroup.Organization", "model.Organization"),
					},
					AccountGroupAssignments: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.AccountGroup.AccountGroupAssignments", "model.AccountGroupAssignment"),
					},
				},
				Account: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account", "model.Account"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.Organization", "model.Organization"),
					},
					ParentAccount: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.ParentAccount", "model.Account"),
					},
					ChildAccounts: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.ChildAccounts", "model.Account"),
					},
					AccountGroupAssignments: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.AccountGroupAssignments", "model.AccountGroupAssignment"),
					},
					BudgetRevisionAccountValues: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Organization", "model.Organization"),
						},
						Budget: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}{
							RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget", "model.Budget"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.Organization", "model.Organization"),
							},
							BudgetRevisions: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions", "model.BudgetRevision"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Organization", "model.Organization"),
								},
								Budget: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Budget", "model.Budget"),
								},
								BudgetRevisionAccountValues: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
								},
							},
							BudgetAccountValues: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues", "model.BudgetAccountValue"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Organization", "model.Organization"),
								},
								Budget: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Budget", "model.Budget"),
								},
								Account: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Account", "model.Account"),
								},
							},
						},
						BudgetRevision: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision", "model.BudgetRevision"),
						},
						Account: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Account", "model.Account"),
						},
					},
					BudgetAccountValues: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.BudgetAccountValues", "model.BudgetAccountValue"),
					},
					TransactionAssignments: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments", "model.TransactionAssignment"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Organization", "model.Organization"),
						},
						Transaction: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction", "model.Transaction_"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.Organization", "model.Organization"),
							},
							CreditLedgerAccount: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount", "model.LedgerAccount"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.Organization", "model.Organization"),
								},
								CreditTransactions: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.CreditTransactions", "model.Transaction_"),
								},
								DebitTransactions: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.DebitTransactions", "model.Transaction_"),
								},
							},
							DebitLedgerAccount: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.DebitLedgerAccount", "model.LedgerAccount"),
							},
							TransactionAssignments: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.TransactionAssignments", "model.TransactionAssignment"),
							},
						},
						Account: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Account", "model.Account"),
						},
					},
				},
			},
			AccountGroups: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.AccountGroups", "model.AccountGroup"),
			},
			Accounts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.Accounts", "model.Account"),
			},
			BudgetRevisions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.BudgetRevisions", "model.BudgetRevision"),
			},
			BudgetRevisionAccountValues: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
			},
			BudgetAccountValues: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.BudgetAccountValues", "model.BudgetAccountValue"),
			},
			Budgets: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.Budgets", "model.Budget"),
			},
			LedgerYears: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Submission.Organization.LedgerYears", "model.LedgerYear"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.Organization.LedgerYears.Organization", "model.Organization"),
				},
			},
			LedgerAccounts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.LedgerAccounts", "model.LedgerAccount"),
			},
			ReportTemplates: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Submission.Organization.ReportTemplates", "model.ReportTemplate"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.Organization.ReportTemplates.Organization", "model.Organization"),
				},
			},
			Reports: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Submission.Organization.Reports", "model.Report"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.Organization.Reports.Organization", "model.Organization"),
				},
			},
			Transactions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.Transactions", "model.Transaction_"),
			},
			TransactionAssignments: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.TransactionAssignments", "model.TransactionAssignment"),
			},
			Committees: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				PaymentAccounts struct {
					field.RelationField
					Committee struct {
						field.RelationField
					}
				}
				Submissions struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Submission.Organization.Committees", "model.Committee"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.Organization.Committees.Organization", "model.Organization"),
				},
				PaymentAccounts: struct {
					field.RelationField
					Committee struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Submission.Organization.Committees.PaymentAccounts", "model.CommitteePaymentAccount"),
					Committee: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Submission.Organization.Committees.PaymentAccounts.Committee", "model.Committee"),
					},
				},
				Submissions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.Organization.Committees.Submissions", "model.Submission"),
				},
			},
			Submissions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Submission.Organization.Submissions", "model.Submission"),
			},
		},
		Committee: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Submission.Committee", "model.Committee"),
		},
		CreatedBy: struct {
			field.RelationField
			UserIdentities struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Submission.CreatedBy", "model.User"),
			UserIdentities: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Submission.CreatedBy.UserIdentities", "model.UserIdentity"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Submission.CreatedBy.UserIdentities.User", "model.User"),
				},
			},
		},
	}

	_submissionComment.Author = submissionCommentBelongsToAuthor{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Author", "model.User"),
	}

	_submissionComment.fillFieldMap()

	return _submissionComment
}

type submissionComment struct {
	submissionCommentDo submissionCommentDo

	ALL          field.Asterisk
	ID           field.Field
	SubmissionID field.Field
	AuthorUserID field.Field
	Content      field.String
	IsAdminOnly  field.Bool
	StatusFrom   field.Int32
	StatusTo     field.Int32
	CreatedAt    field.Time
	Submission   submissionCommentBelongsToSubmission

	Author submissionCommentBelongsToAuthor

	fieldMap map[string]field.Expr
}

func (s submissionComment) Table(newTableName string) *submissionComment {
	s.submissionCommentDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s submissionComment) As(alias string) *submissionComment {
	s.submissionCommentDo.DO = *(s.submissionCommentDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *submissionComment) updateTableName(table string) *submissionComment {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewField(table, "id")
	s.SubmissionID = field.NewField(table, "submission_id")
	s.AuthorUserID = field.NewField(table, "author_user_id")
	s.Content = field.NewString(table, "content")
	s.IsAdminOnly = field.NewBool(table, "is_admin_only")
	s.StatusFrom = field.NewInt32(table, "status_from")
	s.StatusTo = field.NewInt32(table, "status_to")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *submissionComment) WithContext(ctx context.Context) ISubmissionCommentDo {
	return s.submissionCommentDo.WithContext(ctx)
}

func (s submissionComment) TableName() string { return s.submissionCommentDo.TableName() }

func (s submissionComment) Alias() string { return s.submissionCommentDo.Alias() }

func (s submissionComment) Columns(cols ...field.Expr) gen.Columns {
	return s.submissionCommentDo.Columns(cols...)
}

func (s *submissionComment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *submissionComment) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["submission_id"] = s.SubmissionID
	s.fieldMap["author_user_id"] = s.AuthorUserID
	s.fieldMap["content"] = s.Content
	s.fieldMap["is_admin_only"] = s.IsAdminOnly
	s.fieldMap["status_from"] = s.StatusFrom
	s.fieldMap["status_to"] = s.StatusTo
	s.fieldMap["created_at"] = s.CreatedAt

}

func (s submissionComment) clone(db *gorm.DB) submissionComment {
	s.submissionCommentDo.ReplaceConnPool(db.Statement.ConnPool)
	s.Submission.db = db.Session(&gorm.Session{Initialized: true})
	s.Submission.db.Statement.ConnPool = db.Statement.ConnPool
	s.Author.db = db.Session(&gorm.Session{Initialized: true})
	s.Author.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s submissionComment) replaceDB(db *gorm.DB) submissionComment {
	s.submissionCommentDo.ReplaceDB(db)
	s.Submission.db = db.Session(&gorm.Session{})
	s.Author.db = db.Session(&gorm.Session{})
	return s
}

type submissionCommentBelongsToSubmission struct {
	db *gorm.DB

	field.RelationField

	Organization struct {
		field.RelationField
		SubmissionSettings struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		AccountGroupAssignments struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroup struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}
			Account struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
				BudgetAccountValues struct {
					field.RelationField
				}
				TransactionAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditLedgerAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitLedgerAccount struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
			}
		}
		AccountGroups struct {
			field.RelationField
		}
		Accounts struct {
			field.RelationField
		}
		BudgetRevisions struct {
			field.RelationField
		}
		BudgetRevisionAccountValues struct {
			field.RelationField
		}
		BudgetAccountValues struct {
			field.RelationField
		}
		Budgets struct {
			field.RelationField
		}
		LedgerYears struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		LedgerAccounts struct {
			field.RelationField
		}
		ReportTemplates struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Reports struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Transactions struct {
			field.RelationField
		}
		TransactionAssignments struct {
			field.RelationField
		}
		Committees struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			PaymentAccounts struct {
				field.RelationField
				Committee struct {
					field.RelationField
				}
			}
			Submissions struct {
				field.RelationField
			}
		}
		Submissions struct {
			field.RelationField
		}
	}
	Committee struct {
		field.RelationField
	}
	CreatedBy struct {
		field.RelationField
		UserIdentities struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}
	}
}

func (a submissionCommentBelongsToSubmission) Where(conds ...field.Expr) *submissionCommentBelongsToSubmission {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a submissionCommentBelongsToSubmission) WithContext(ctx context.Context) *submissionCommentBelongsToSubmission {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a submissionCommentBelongsToSubmission) Session(session *gorm.Session) *submissionCommentBelongsToSubmission {
	a.db = a.db.Session(session)
	return &a
}

func (a submissionCommentBelongsToSubmission) Model(m *model.SubmissionComment) *submissionCommentBelongsToSubmissionTx {
	return &submissionCommentBelongsToSubmissionTx{a.db.Model(m).Association(a.Name())}
}

func (a submissionCommentBelongsToSubmission) Unscoped() *submissionCommentBelongsToSubmission {
	a.db = a.db.Unscoped()
	return &a
}

type submissionCommentBelongsToSubmissionTx struct{ tx *gorm.Association }

func (a submissionCommentBelongsToSubmissionTx) Find() (result *model.Submission, err error) {
	return result, a.tx.Find(&result)
}

func (a submissionCommentBelongsToSubmissionTx) Append(values ...*model.Submission) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a submissionCommentBelongsToSubmissionTx) Replace(values ...*model.Submission) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a submissionCommentBelongsToSubmissionTx) Delete(values ...*model.Submission) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a submissionCommentBelongsToSubmissionTx) Clear() error {
	return a.tx.Clear()
}

func (a submissionCommentBelongsToSubmissionTx) Count() int64 {
	return a.tx.Count()
}

func (a submissionCommentBelongsToSubmissionTx) Unscoped() *submissionCommentBelongsToSubmissionTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type submissionCommentBelongsToAuthor struct {
	db *gorm.DB

	field.RelationField
}

func (a submissionCommentBelongsToAuthor) Where(conds ...field.Expr) *submissionCommentBelongsToAuthor {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a submissionCommentBelongsToAuthor) WithContext(ctx context.Context) *submissionCommentBelongsToAuthor {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a submissionCommentBelongsToAuthor) Session(session *gorm.Session) *submissionCommentBelongsToAuthor {
	a.db = a.db.Session(session)
	return &a
}

func (a submissionCommentBelongsToAuthor) Model(m *model.SubmissionComment) *submissionCommentBelongsToAuthorTx {
	return &submissionCommentBelongsToAuthorTx{a.db.Model(m).Association(a.Name())}
}

func (a submissionCommentBelongsToAuthor) Unscoped() *submissionCommentBelongsToAuthor {
	a.db = a.db.Unscoped()
	return &a
}

type submissionCommentBelongsToAuthorTx struct{ tx *gorm.Association }

func (a submissionCommentBelongsToAuthorTx) Find() (result *model.User, err error) {
	return result, a.tx.Find(&result)
}

func (a submissionCommentBelongsToAuthorTx) Append(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a submissionCommentBelongsToAuthorTx) Replace(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a submissionCommentBelongsToAuthorTx) Delete(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a submissionCommentBelongsToAuthorTx) Clear() error {
	return a.tx.Clear()
}

func (a submissionCommentBelongsToAuthorTx) Count() int64 {
	return a.tx.Count()
}

func (a submissionCommentBelongsToAuthorTx) Unscoped() *submissionCommentBelongsToAuthorTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type submissionCommentDo struct{ gen.DO }

type ISubmissionCommentDo interface {
	gen.SubQuery
	Debug() ISubmissionCommentDo
	WithContext(ctx context.Context) ISubmissionCommentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISubmissionCommentDo
	WriteDB() ISubmissionCommentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISubmissionCommentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISubmissionCommentDo
	Not(conds ...gen.Condition) ISubmissionCommentDo
	Or(conds ...gen.Condition) ISubmissionCommentDo
	Select(conds ...field.Expr) ISubmissionCommentDo
	Where(conds ...gen.Condition) ISubmissionCommentDo
	Order(conds ...field.Expr) ISubmissionCommentDo
	Distinct(cols ...field.Expr) ISubmissionCommentDo
	Omit(cols ...field.Expr) ISubmissionCommentDo
	Join(table schema.Tabler, on ...field.Expr) ISubmissionCommentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISubmissionCommentDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISubmissionCommentDo
	Group(cols ...field.Expr) ISubmissionCommentDo
	Having(conds ...gen.Condition) ISubmissionCommentDo
	Limit(limit int) ISubmissionCommentDo
	Offset(offset int) ISubmissionCommentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISubmissionCommentDo
	Unscoped() ISubmissionCommentDo
	Create(values ...*model.SubmissionComment) error
	CreateInBatches(values []*model.SubmissionComment, batchSize int) error
	Save(values ...*model.SubmissionComment) error
	First() (*model.SubmissionComment, error)
	Take() (*model.SubmissionComment, error)
	Last() (*model.SubmissionComment, error)
	Find() ([]*model.SubmissionComment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SubmissionComment, err error)
	FindInBatches(result *[]*model.SubmissionComment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SubmissionComment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISubmissionCommentDo
	Assign(attrs ...field.AssignExpr) ISubmissionCommentDo
	Joins(fields ...field.RelationField) ISubmissionCommentDo
	Preload(fields ...field.RelationField) ISubmissionCommentDo
	FirstOrInit() (*model.SubmissionComment, error)
	FirstOrCreate() (*model.SubmissionComment, error)
	FindByPage(offset int, limit int) (result []*model.SubmissionComment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISubmissionCommentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s submissionCommentDo) Debug() ISubmissionCommentDo {
	return s.withDO(s.DO.Debug())
}

func (s submissionCommentDo) WithContext(ctx context.Context) ISubmissionCommentDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s submissionCommentDo) ReadDB() ISubmissionCommentDo {
	return s.Clauses(dbresolver.Read)
}

func (s submissionCommentDo) WriteDB() ISubmissionCommentDo {
	return s.Clauses(dbresolver.Write)
}

func (s submissionCommentDo) Session(config *gorm.Session) ISubmissionCommentDo {
	return s.withDO(s.DO.Session(config))
}

func (s submissionCommentDo) Clauses(conds ...clause.Expression) ISubmissionCommentDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s submissionCommentDo) Returning(value interface{}, columns ...string) ISubmissionCommentDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s submissionCommentDo) Not(conds ...gen.Condition) ISubmissionCommentDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s submissionCommentDo) Or(conds ...gen.Condition) ISubmissionCommentDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s submissionCommentDo) Select(conds ...field.Expr) ISubmissionCommentDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s submissionCommentDo) Where(conds ...gen.Condition) ISubmissionCommentDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s submissionCommentDo) Order(conds ...field.Expr) ISubmissionCommentDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s submissionCommentDo) Distinct(cols ...field.Expr) ISubmissionCommentDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s submissionCommentDo) Omit(cols ...field.Expr) ISubmissionCommentDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s submissionCommentDo) Join(table schema.Tabler, on ...field.Expr) ISubmissionCommentDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s submissionCommentDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISubmissionCommentDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s submissionCommentDo) RightJoin(table schema.Tabler, on ...field.Expr) ISubmissionCommentDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s submissionCommentDo) Group(cols ...field.Expr) ISubmissionCommentDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s submissionCommentDo) Having(conds ...gen.Condition) ISubmissionCommentDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s submissionCommentDo) Limit(limit int) ISubmissionCommentDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s submissionCommentDo) Offset(offset int) ISubmissionCommentDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s submissionCommentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISubmissionCommentDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s submissionCommentDo) Unscoped() ISubmissionCommentDo {
	return s.withDO(s.DO.Unscoped())
}

func (s submissionCommentDo) Create(values ...*model.SubmissionComment) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s submissionCommentDo) CreateInBatches(values []*model.SubmissionComment, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s submissionCommentDo) Save(values ...*model.SubmissionComment) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s submissionCommentDo) First() (*model.SubmissionComment, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubmissionComment), nil
	}
}

func (s submissionCommentDo) Take() (*model.SubmissionComment, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubmissionComment), nil
	}
}

func (s submissionCommentDo) Last() (*model.SubmissionComment, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubmissionComment), nil
	}
}

func (s submissionCommentDo) Find() ([]*model.SubmissionComment, error) {
	result, err := s.DO.Find()
	return result.([]*model.SubmissionComment), err
}

func (s submissionCommentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SubmissionComment, err error) {
	buf := make([]*model.SubmissionComment, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s submissionCommentDo) FindInBatches(result *[]*model.SubmissionComment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s submissionCommentDo) Attrs(attrs ...field.AssignExpr) ISubmissionCommentDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s submissionCommentDo) Assign(attrs ...field.AssignExpr) ISubmissionCommentDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s submissionCommentDo) Joins(fields ...field.RelationField) ISubmissionCommentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s submissionCommentDo) Preload(fields ...field.RelationField) ISubmissionCommentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s submissionCommentDo) FirstOrInit() (*model.SubmissionComment, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubmissionComment), nil
	}
}

func (s submissionCommentDo) FirstOrCreate() (*model.SubmissionComment, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubmissionComment), nil
	}
}

func (s submissionCommentDo) FindByPage(offset int, limit int) (result []*model.SubmissionComment, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s submissionCommentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s submissionCommentDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s submissionCommentDo) Delete(models ...*model.SubmissionComment) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *submissionCommentDo) withDO(do gen.Dao) *submissionCommentDo {
	s.DO = *do.(*gen.DO)
	return s
}
