// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"github.com/pixlcrashr/vsfv/pkg/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSubmissionAttachment(db *gorm.DB, opts ...gen.DOOption) submissionAttachment {
	_submissionAttachment := submissionAttachment{}

	_submissionAttachment.submissionAttachmentDo.UseDB(db, opts...)
	_submissionAttachment.submissionAttachmentDo.UseModel(&model.SubmissionAttachment{})

	tableName := _submissionAttachment.submissionAttachmentDo.TableName()
	_submissionAttachment.ALL = field.NewAsterisk(tableName)
	_submissionAttachment.ID = field.NewField(tableName, "id")
	_submissionAttachment.SubmissionItemID = field.NewField(tableName, "submission_item_id")
	_submissionAttachment.FileName = field.NewString(tableName, "file_name")
	_submissionAttachment.MimeType = field.NewString(tableName, "mime_type")
	_submissionAttachment.FileSize = field.NewInt64(tableName, "file_size")
	_submissionAttachment.StorageKey = field.NewString(tableName, "storage_key")
	_submissionAttachment.CreatedAt = field.NewTime(tableName, "created_at")
	_submissionAttachment.SubmissionItem = submissionAttachmentBelongsToSubmissionItem{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SubmissionItem", "model.SubmissionItem"),
		Submission: struct {
			field.RelationField
			Organization struct {
				field.RelationField
				SubmissionSettings struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
				}
				AccountGroupAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroup struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						AccountGroupAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						ParentAccount struct {
							field.RelationField
						}
						ChildAccounts struct {
							field.RelationField
						}
						AccountGroupAssignments struct {
							field.RelationField
						}
						BudgetRevisionAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								BudgetRevisions struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									BudgetRevisionAccountValues struct {
										field.RelationField
									}
								}
								BudgetAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
							}
							BudgetRevision struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Transaction struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditLedgerAccount struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									CreditTransactions struct {
										field.RelationField
									}
									DebitTransactions struct {
										field.RelationField
									}
								}
								DebitLedgerAccount struct {
									field.RelationField
								}
								TransactionAssignments struct {
									field.RelationField
								}
							}
							Account struct {
								field.RelationField
							}
						}
					}
				}
				AccountGroups struct {
					field.RelationField
				}
				Accounts struct {
					field.RelationField
				}
				BudgetRevisions struct {
					field.RelationField
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
				}
				BudgetAccountValues struct {
					field.RelationField
				}
				Budgets struct {
					field.RelationField
				}
				LedgerYears struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
				}
				LedgerAccounts struct {
					field.RelationField
				}
				ReportTemplates struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
				}
				Reports struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
				}
				Transactions struct {
					field.RelationField
				}
				TransactionAssignments struct {
					field.RelationField
				}
				Committees struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					PaymentAccounts struct {
						field.RelationField
						Committee struct {
							field.RelationField
						}
					}
					Submissions struct {
						field.RelationField
					}
				}
				Submissions struct {
					field.RelationField
				}
			}
			Committee struct {
				field.RelationField
			}
			CreatedBy struct {
				field.RelationField
				UserIdentities struct {
					field.RelationField
					User struct {
						field.RelationField
					}
				}
			}
		}{
			RelationField: field.NewRelation("SubmissionItem.Submission", "model.Submission"),
			Organization: struct {
				field.RelationField
				SubmissionSettings struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
				}
				AccountGroupAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroup struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						AccountGroupAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						ParentAccount struct {
							field.RelationField
						}
						ChildAccounts struct {
							field.RelationField
						}
						AccountGroupAssignments struct {
							field.RelationField
						}
						BudgetRevisionAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								BudgetRevisions struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									BudgetRevisionAccountValues struct {
										field.RelationField
									}
								}
								BudgetAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
							}
							BudgetRevision struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Transaction struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditLedgerAccount struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									CreditTransactions struct {
										field.RelationField
									}
									DebitTransactions struct {
										field.RelationField
									}
								}
								DebitLedgerAccount struct {
									field.RelationField
								}
								TransactionAssignments struct {
									field.RelationField
								}
							}
							Account struct {
								field.RelationField
							}
						}
					}
				}
				AccountGroups struct {
					field.RelationField
				}
				Accounts struct {
					field.RelationField
				}
				BudgetRevisions struct {
					field.RelationField
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
				}
				BudgetAccountValues struct {
					field.RelationField
				}
				Budgets struct {
					field.RelationField
				}
				LedgerYears struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
				}
				LedgerAccounts struct {
					field.RelationField
				}
				ReportTemplates struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
				}
				Reports struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
				}
				Transactions struct {
					field.RelationField
				}
				TransactionAssignments struct {
					field.RelationField
				}
				Committees struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					PaymentAccounts struct {
						field.RelationField
						Committee struct {
							field.RelationField
						}
					}
					Submissions struct {
						field.RelationField
					}
				}
				Submissions struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("SubmissionItem.Submission.Organization", "model.Organization"),
				SubmissionSettings: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.SubmissionSettings", "model.OrganizationSubmissionSettings"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("SubmissionItem.Submission.Organization.SubmissionSettings.Organization", "model.Organization"),
					},
				},
				AccountGroupAssignments: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroup struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						AccountGroupAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						ParentAccount struct {
							field.RelationField
						}
						ChildAccounts struct {
							field.RelationField
						}
						AccountGroupAssignments struct {
							field.RelationField
						}
						BudgetRevisionAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								BudgetRevisions struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									BudgetRevisionAccountValues struct {
										field.RelationField
									}
								}
								BudgetAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
							}
							BudgetRevision struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Transaction struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditLedgerAccount struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									CreditTransactions struct {
										field.RelationField
									}
									DebitTransactions struct {
										field.RelationField
									}
								}
								DebitLedgerAccount struct {
									field.RelationField
								}
								TransactionAssignments struct {
									field.RelationField
								}
							}
							Account struct {
								field.RelationField
							}
						}
					}
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments", "model.AccountGroupAssignment"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Organization", "model.Organization"),
					},
					AccountGroup: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						AccountGroupAssignments struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.AccountGroup", "model.AccountGroup"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.AccountGroup.Organization", "model.Organization"),
						},
						AccountGroupAssignments: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.AccountGroup.AccountGroupAssignments", "model.AccountGroupAssignment"),
						},
					},
					Account: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						ParentAccount struct {
							field.RelationField
						}
						ChildAccounts struct {
							field.RelationField
						}
						AccountGroupAssignments struct {
							field.RelationField
						}
						BudgetRevisionAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								BudgetRevisions struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									BudgetRevisionAccountValues struct {
										field.RelationField
									}
								}
								BudgetAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
							}
							BudgetRevision struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Transaction struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditLedgerAccount struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									CreditTransactions struct {
										field.RelationField
									}
									DebitTransactions struct {
										field.RelationField
									}
								}
								DebitLedgerAccount struct {
									field.RelationField
								}
								TransactionAssignments struct {
									field.RelationField
								}
							}
							Account struct {
								field.RelationField
							}
						}
					}{
						RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account", "model.Account"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.Organization", "model.Organization"),
						},
						ParentAccount: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.ParentAccount", "model.Account"),
						},
						ChildAccounts: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.ChildAccounts", "model.Account"),
						},
						AccountGroupAssignments: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.AccountGroupAssignments", "model.AccountGroupAssignment"),
						},
						BudgetRevisionAccountValues: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								BudgetRevisions struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									BudgetRevisionAccountValues struct {
										field.RelationField
									}
								}
								BudgetAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
							}
							BudgetRevision struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Organization", "model.Organization"),
							},
							Budget: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								BudgetRevisions struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									BudgetRevisionAccountValues struct {
										field.RelationField
									}
								}
								BudgetAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
							}{
								RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget", "model.Budget"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.Organization", "model.Organization"),
								},
								BudgetRevisions: struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									BudgetRevisionAccountValues struct {
										field.RelationField
									}
								}{
									RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions", "model.BudgetRevision"),
									Organization: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Organization", "model.Organization"),
									},
									Budget: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Budget", "model.Budget"),
									},
									BudgetRevisionAccountValues: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
									},
								},
								BudgetAccountValues: struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}{
									RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues", "model.BudgetAccountValue"),
									Organization: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Organization", "model.Organization"),
									},
									Budget: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Budget", "model.Budget"),
									},
									Account: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Account", "model.Account"),
									},
								},
							},
							BudgetRevision: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision", "model.BudgetRevision"),
							},
							Account: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Account", "model.Account"),
							},
						},
						BudgetAccountValues: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.BudgetAccountValues", "model.BudgetAccountValue"),
						},
						TransactionAssignments: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Transaction struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditLedgerAccount struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									CreditTransactions struct {
										field.RelationField
									}
									DebitTransactions struct {
										field.RelationField
									}
								}
								DebitLedgerAccount struct {
									field.RelationField
								}
								TransactionAssignments struct {
									field.RelationField
								}
							}
							Account struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments", "model.TransactionAssignment"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Organization", "model.Organization"),
							},
							Transaction: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditLedgerAccount struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									CreditTransactions struct {
										field.RelationField
									}
									DebitTransactions struct {
										field.RelationField
									}
								}
								DebitLedgerAccount struct {
									field.RelationField
								}
								TransactionAssignments struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction", "model.Transaction_"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.Organization", "model.Organization"),
								},
								CreditLedgerAccount: struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									CreditTransactions struct {
										field.RelationField
									}
									DebitTransactions struct {
										field.RelationField
									}
								}{
									RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount", "model.LedgerAccount"),
									Organization: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.Organization", "model.Organization"),
									},
									CreditTransactions: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.CreditTransactions", "model.Transaction_"),
									},
									DebitTransactions: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.DebitTransactions", "model.Transaction_"),
									},
								},
								DebitLedgerAccount: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.DebitLedgerAccount", "model.LedgerAccount"),
								},
								TransactionAssignments: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.TransactionAssignments", "model.TransactionAssignment"),
								},
							},
							Account: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroupAssignments.Account.TransactionAssignments.Account", "model.Account"),
							},
						},
					},
				},
				AccountGroups: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.AccountGroups", "model.AccountGroup"),
				},
				Accounts: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.Accounts", "model.Account"),
				},
				BudgetRevisions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.BudgetRevisions", "model.BudgetRevision"),
				},
				BudgetRevisionAccountValues: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
				},
				BudgetAccountValues: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.BudgetAccountValues", "model.BudgetAccountValue"),
				},
				Budgets: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.Budgets", "model.Budget"),
				},
				LedgerYears: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.LedgerYears", "model.LedgerYear"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("SubmissionItem.Submission.Organization.LedgerYears.Organization", "model.Organization"),
					},
				},
				LedgerAccounts: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.LedgerAccounts", "model.LedgerAccount"),
				},
				ReportTemplates: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.ReportTemplates", "model.ReportTemplate"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("SubmissionItem.Submission.Organization.ReportTemplates.Organization", "model.Organization"),
					},
				},
				Reports: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.Reports", "model.Report"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("SubmissionItem.Submission.Organization.Reports.Organization", "model.Organization"),
					},
				},
				Transactions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.Transactions", "model.Transaction_"),
				},
				TransactionAssignments: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.TransactionAssignments", "model.TransactionAssignment"),
				},
				Committees: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					PaymentAccounts struct {
						field.RelationField
						Committee struct {
							field.RelationField
						}
					}
					Submissions struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.Committees", "model.Committee"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("SubmissionItem.Submission.Organization.Committees.Organization", "model.Organization"),
					},
					PaymentAccounts: struct {
						field.RelationField
						Committee struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("SubmissionItem.Submission.Organization.Committees.PaymentAccounts", "model.CommitteePaymentAccount"),
						Committee: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("SubmissionItem.Submission.Organization.Committees.PaymentAccounts.Committee", "model.Committee"),
						},
					},
					Submissions: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("SubmissionItem.Submission.Organization.Committees.Submissions", "model.Submission"),
					},
				},
				Submissions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.Organization.Submissions", "model.Submission"),
				},
			},
			Committee: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("SubmissionItem.Submission.Committee", "model.Committee"),
			},
			CreatedBy: struct {
				field.RelationField
				UserIdentities struct {
					field.RelationField
					User struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("SubmissionItem.Submission.CreatedBy", "model.User"),
				UserIdentities: struct {
					field.RelationField
					User struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("SubmissionItem.Submission.CreatedBy.UserIdentities", "model.UserIdentity"),
					User: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("SubmissionItem.Submission.CreatedBy.UserIdentities.User", "model.User"),
					},
				},
			},
		},
		OriginalReceivedBy: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("SubmissionItem.OriginalReceivedBy", "model.User"),
		},
	}

	_submissionAttachment.fillFieldMap()

	return _submissionAttachment
}

type submissionAttachment struct {
	submissionAttachmentDo submissionAttachmentDo

	ALL              field.Asterisk
	ID               field.Field
	SubmissionItemID field.Field
	FileName         field.String
	MimeType         field.String
	FileSize         field.Int64
	StorageKey       field.String
	CreatedAt        field.Time
	SubmissionItem   submissionAttachmentBelongsToSubmissionItem

	fieldMap map[string]field.Expr
}

func (s submissionAttachment) Table(newTableName string) *submissionAttachment {
	s.submissionAttachmentDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s submissionAttachment) As(alias string) *submissionAttachment {
	s.submissionAttachmentDo.DO = *(s.submissionAttachmentDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *submissionAttachment) updateTableName(table string) *submissionAttachment {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewField(table, "id")
	s.SubmissionItemID = field.NewField(table, "submission_item_id")
	s.FileName = field.NewString(table, "file_name")
	s.MimeType = field.NewString(table, "mime_type")
	s.FileSize = field.NewInt64(table, "file_size")
	s.StorageKey = field.NewString(table, "storage_key")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *submissionAttachment) WithContext(ctx context.Context) ISubmissionAttachmentDo {
	return s.submissionAttachmentDo.WithContext(ctx)
}

func (s submissionAttachment) TableName() string { return s.submissionAttachmentDo.TableName() }

func (s submissionAttachment) Alias() string { return s.submissionAttachmentDo.Alias() }

func (s submissionAttachment) Columns(cols ...field.Expr) gen.Columns {
	return s.submissionAttachmentDo.Columns(cols...)
}

func (s *submissionAttachment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *submissionAttachment) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["submission_item_id"] = s.SubmissionItemID
	s.fieldMap["file_name"] = s.FileName
	s.fieldMap["mime_type"] = s.MimeType
	s.fieldMap["file_size"] = s.FileSize
	s.fieldMap["storage_key"] = s.StorageKey
	s.fieldMap["created_at"] = s.CreatedAt

}

func (s submissionAttachment) clone(db *gorm.DB) submissionAttachment {
	s.submissionAttachmentDo.ReplaceConnPool(db.Statement.ConnPool)
	s.SubmissionItem.db = db.Session(&gorm.Session{Initialized: true})
	s.SubmissionItem.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s submissionAttachment) replaceDB(db *gorm.DB) submissionAttachment {
	s.submissionAttachmentDo.ReplaceDB(db)
	s.SubmissionItem.db = db.Session(&gorm.Session{})
	return s
}

type submissionAttachmentBelongsToSubmissionItem struct {
	db *gorm.DB

	field.RelationField

	Submission struct {
		field.RelationField
		Organization struct {
			field.RelationField
			SubmissionSettings struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			AccountGroupAssignments struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								BudgetRevisionAccountValues struct {
									field.RelationField
								}
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevision struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditLedgerAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitLedgerAccount struct {
								field.RelationField
							}
							TransactionAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
				}
			}
			AccountGroups struct {
				field.RelationField
			}
			Accounts struct {
				field.RelationField
			}
			BudgetRevisions struct {
				field.RelationField
			}
			BudgetRevisionAccountValues struct {
				field.RelationField
			}
			BudgetAccountValues struct {
				field.RelationField
			}
			Budgets struct {
				field.RelationField
			}
			LedgerYears struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			LedgerAccounts struct {
				field.RelationField
			}
			ReportTemplates struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Reports struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Transactions struct {
				field.RelationField
			}
			TransactionAssignments struct {
				field.RelationField
			}
			Committees struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				PaymentAccounts struct {
					field.RelationField
					Committee struct {
						field.RelationField
					}
				}
				Submissions struct {
					field.RelationField
				}
			}
			Submissions struct {
				field.RelationField
			}
		}
		Committee struct {
			field.RelationField
		}
		CreatedBy struct {
			field.RelationField
			UserIdentities struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}
		}
	}
	OriginalReceivedBy struct {
		field.RelationField
	}
}

func (a submissionAttachmentBelongsToSubmissionItem) Where(conds ...field.Expr) *submissionAttachmentBelongsToSubmissionItem {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a submissionAttachmentBelongsToSubmissionItem) WithContext(ctx context.Context) *submissionAttachmentBelongsToSubmissionItem {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a submissionAttachmentBelongsToSubmissionItem) Session(session *gorm.Session) *submissionAttachmentBelongsToSubmissionItem {
	a.db = a.db.Session(session)
	return &a
}

func (a submissionAttachmentBelongsToSubmissionItem) Model(m *model.SubmissionAttachment) *submissionAttachmentBelongsToSubmissionItemTx {
	return &submissionAttachmentBelongsToSubmissionItemTx{a.db.Model(m).Association(a.Name())}
}

func (a submissionAttachmentBelongsToSubmissionItem) Unscoped() *submissionAttachmentBelongsToSubmissionItem {
	a.db = a.db.Unscoped()
	return &a
}

type submissionAttachmentBelongsToSubmissionItemTx struct{ tx *gorm.Association }

func (a submissionAttachmentBelongsToSubmissionItemTx) Find() (result *model.SubmissionItem, err error) {
	return result, a.tx.Find(&result)
}

func (a submissionAttachmentBelongsToSubmissionItemTx) Append(values ...*model.SubmissionItem) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a submissionAttachmentBelongsToSubmissionItemTx) Replace(values ...*model.SubmissionItem) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a submissionAttachmentBelongsToSubmissionItemTx) Delete(values ...*model.SubmissionItem) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a submissionAttachmentBelongsToSubmissionItemTx) Clear() error {
	return a.tx.Clear()
}

func (a submissionAttachmentBelongsToSubmissionItemTx) Count() int64 {
	return a.tx.Count()
}

func (a submissionAttachmentBelongsToSubmissionItemTx) Unscoped() *submissionAttachmentBelongsToSubmissionItemTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type submissionAttachmentDo struct{ gen.DO }

type ISubmissionAttachmentDo interface {
	gen.SubQuery
	Debug() ISubmissionAttachmentDo
	WithContext(ctx context.Context) ISubmissionAttachmentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISubmissionAttachmentDo
	WriteDB() ISubmissionAttachmentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISubmissionAttachmentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISubmissionAttachmentDo
	Not(conds ...gen.Condition) ISubmissionAttachmentDo
	Or(conds ...gen.Condition) ISubmissionAttachmentDo
	Select(conds ...field.Expr) ISubmissionAttachmentDo
	Where(conds ...gen.Condition) ISubmissionAttachmentDo
	Order(conds ...field.Expr) ISubmissionAttachmentDo
	Distinct(cols ...field.Expr) ISubmissionAttachmentDo
	Omit(cols ...field.Expr) ISubmissionAttachmentDo
	Join(table schema.Tabler, on ...field.Expr) ISubmissionAttachmentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISubmissionAttachmentDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISubmissionAttachmentDo
	Group(cols ...field.Expr) ISubmissionAttachmentDo
	Having(conds ...gen.Condition) ISubmissionAttachmentDo
	Limit(limit int) ISubmissionAttachmentDo
	Offset(offset int) ISubmissionAttachmentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISubmissionAttachmentDo
	Unscoped() ISubmissionAttachmentDo
	Create(values ...*model.SubmissionAttachment) error
	CreateInBatches(values []*model.SubmissionAttachment, batchSize int) error
	Save(values ...*model.SubmissionAttachment) error
	First() (*model.SubmissionAttachment, error)
	Take() (*model.SubmissionAttachment, error)
	Last() (*model.SubmissionAttachment, error)
	Find() ([]*model.SubmissionAttachment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SubmissionAttachment, err error)
	FindInBatches(result *[]*model.SubmissionAttachment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SubmissionAttachment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISubmissionAttachmentDo
	Assign(attrs ...field.AssignExpr) ISubmissionAttachmentDo
	Joins(fields ...field.RelationField) ISubmissionAttachmentDo
	Preload(fields ...field.RelationField) ISubmissionAttachmentDo
	FirstOrInit() (*model.SubmissionAttachment, error)
	FirstOrCreate() (*model.SubmissionAttachment, error)
	FindByPage(offset int, limit int) (result []*model.SubmissionAttachment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISubmissionAttachmentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s submissionAttachmentDo) Debug() ISubmissionAttachmentDo {
	return s.withDO(s.DO.Debug())
}

func (s submissionAttachmentDo) WithContext(ctx context.Context) ISubmissionAttachmentDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s submissionAttachmentDo) ReadDB() ISubmissionAttachmentDo {
	return s.Clauses(dbresolver.Read)
}

func (s submissionAttachmentDo) WriteDB() ISubmissionAttachmentDo {
	return s.Clauses(dbresolver.Write)
}

func (s submissionAttachmentDo) Session(config *gorm.Session) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Session(config))
}

func (s submissionAttachmentDo) Clauses(conds ...clause.Expression) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s submissionAttachmentDo) Returning(value interface{}, columns ...string) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s submissionAttachmentDo) Not(conds ...gen.Condition) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s submissionAttachmentDo) Or(conds ...gen.Condition) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s submissionAttachmentDo) Select(conds ...field.Expr) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s submissionAttachmentDo) Where(conds ...gen.Condition) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s submissionAttachmentDo) Order(conds ...field.Expr) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s submissionAttachmentDo) Distinct(cols ...field.Expr) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s submissionAttachmentDo) Omit(cols ...field.Expr) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s submissionAttachmentDo) Join(table schema.Tabler, on ...field.Expr) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s submissionAttachmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISubmissionAttachmentDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s submissionAttachmentDo) RightJoin(table schema.Tabler, on ...field.Expr) ISubmissionAttachmentDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s submissionAttachmentDo) Group(cols ...field.Expr) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s submissionAttachmentDo) Having(conds ...gen.Condition) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s submissionAttachmentDo) Limit(limit int) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s submissionAttachmentDo) Offset(offset int) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s submissionAttachmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s submissionAttachmentDo) Unscoped() ISubmissionAttachmentDo {
	return s.withDO(s.DO.Unscoped())
}

func (s submissionAttachmentDo) Create(values ...*model.SubmissionAttachment) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s submissionAttachmentDo) CreateInBatches(values []*model.SubmissionAttachment, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s submissionAttachmentDo) Save(values ...*model.SubmissionAttachment) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s submissionAttachmentDo) First() (*model.SubmissionAttachment, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubmissionAttachment), nil
	}
}

func (s submissionAttachmentDo) Take() (*model.SubmissionAttachment, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubmissionAttachment), nil
	}
}

func (s submissionAttachmentDo) Last() (*model.SubmissionAttachment, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubmissionAttachment), nil
	}
}

func (s submissionAttachmentDo) Find() ([]*model.SubmissionAttachment, error) {
	result, err := s.DO.Find()
	return result.([]*model.SubmissionAttachment), err
}

func (s submissionAttachmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SubmissionAttachment, err error) {
	buf := make([]*model.SubmissionAttachment, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s submissionAttachmentDo) FindInBatches(result *[]*model.SubmissionAttachment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s submissionAttachmentDo) Attrs(attrs ...field.AssignExpr) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s submissionAttachmentDo) Assign(attrs ...field.AssignExpr) ISubmissionAttachmentDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s submissionAttachmentDo) Joins(fields ...field.RelationField) ISubmissionAttachmentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s submissionAttachmentDo) Preload(fields ...field.RelationField) ISubmissionAttachmentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s submissionAttachmentDo) FirstOrInit() (*model.SubmissionAttachment, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubmissionAttachment), nil
	}
}

func (s submissionAttachmentDo) FirstOrCreate() (*model.SubmissionAttachment, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubmissionAttachment), nil
	}
}

func (s submissionAttachmentDo) FindByPage(offset int, limit int) (result []*model.SubmissionAttachment, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s submissionAttachmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s submissionAttachmentDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s submissionAttachmentDo) Delete(models ...*model.SubmissionAttachment) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *submissionAttachmentDo) withDO(do gen.Dao) *submissionAttachmentDo {
	s.DO = *do.(*gen.DO)
	return s
}
